### ISSUE TITLE
Consistent naming for developers, website, organizations and repositories

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1018]
Currently we have several contexts in which the name of developers and organizations must be specified. This should be made uniform and consistent

Github Organization - reproducible-biomedical-modeling
Docker Organization- crbm
Developer Groups - Center for Reproducible Biomedical Modeling, Biosimulations Developers, Karr Lab, Uconn Health
Email- info@biosimulations.org, info@reproduciblebiomodels.org
Login- auth.biosimulations.org, CRBM Account 

Possible directions:

1. Keep the center name prominent, treat Biosimulations as one of many services/products
2. Focus on the Biosimulations name for everything, attribute work to the Biosimulations Developers. 

If we go with 2, should we rename/recreate the GitHub and docker organizations?

**Comment by jonrkarr** [comment]
I suggested this previously. My preference is to separate CRBM from BioSimulations because most users of BioSimulations won't know what the center is.

This easiest way to do this is probably the following:
- Rename the GitHub organization to `BioSimulations` (or `biosimulations` to be case consistent everywhere)
- Rename the Docker Hub organization to `biosimulations`
- Create a new GitHub organization for the center. This should be able to use the existing name `reproducible-biomedical-modeling`
- Move the `OMEX_Metadata_Spec` repo to the new GitHub organization for the center
- For email, use info@biosimulations.org
- Rename the login domain to `BioSimulations`

**Comment by gmarupilla** [comment]
In my opinion, @jonrkarr approach is appropriate, that way we don't lose the reference to `center` and still would be able to make `biosimulations` project more consistent.

**Comment by biosimulations-daemon** [comment]
- [x]  Rename the GitHub organization to `BioSimulations` (or `biosimulations` to be case consistent everywhere)
- [x]  Create a new GitHub organization for BioSimulators and move the BioSimulators-related repos to this new BioSimulators organization
- [x]  Create a Docker Hub namespace for `biosimulations`
- [x]  Create a Docker Hub namepace for `biosimulators` and move the BioSimulators-related containers here
- [x]  Create a new GitHub organization for the center. This should be able to use the existing name `reproducible-biomedical-modeling`
- [x]  Move the `OMEX_Metadata_Spec` repo to the new GitHub organization for the center
- [x]  Rename the login domain to `BioSimulations`

**Comment by jonrkarr** [comment]
@bilalshaikh42 is this finished?

**Comment by bilalshaikh42** [comment]
Yes, just finished the setup of auth0. I have sent an email to the auth0 sales team about extending our open source subscription (seems to not be offered anymore) to the biosimulations tenant, but all logos/names are set to BioSimulations.
