### ISSUE TITLE
Initial loading of page seems slow

### ISSUE THREAD

**Issue by lzy7071** [reproducible-biomedical-modeling/CRBM-Viz#103]
The first loading of the page address "https://crbm-viz.herokuapp.com/" seems a bit slow, both on mobile network and ethernet connections.

**Comment by bilalshaikh42** [comment]
Thanks for letting me know. 
I can't seem to figure out if this is due to caching or the Heroku-app being asleep by default until it is pinged. 
Could you open the link in a browser, and then use a separate incognito window to try again? The first ping should wake up the server, while the incognito window assures that there is no browser cache being used to speed up the subsequent load.

**Comment by lzy7071** [comment]
The sleeping by default might be the cause then because I did try opening another page load incognito and it opened much quicker than the initial load.

**Comment by bilalshaikh42** [comment]
Great, thanks!
