### ISSUE TITLE
Choose clearer subdomains for the standalone web app and its API

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1051]
Currently, these are the subdomains for the standalone app and its API. 
- https://submit.biosimulations.dev/
- https://dispatch.biosimulations.dev/

I think both names could be clearer, especially the API name. (a) From the subdomains, I don't think its clear how dispatch differs from submit. (b) I don't think "submit" is 100% clear because resources are also submitted to the platform app.

I suggest these subdomains. "run" is short, and it emphasizes simulation execution.
- https://run.biosimulations.dev/
- https://api.run.biosimulations.dev/

Another option is "simulate". This also emphasizes execution, but is longer.
- https://simulate.biosimulations.dev/
- https://api.simulate.biosimulations.dev/

If you prefer not to do subsubdomains, an alternative is https://run-api.biosimulations.dev/ or https://simulate-api.biosimulations.dev/

**Comment by bilalshaikh42** [comment]
I agree that the names are not clear. Ideally, rather than using so many subdomains, I am hoping to just use paths. So simulate.biosimulations.org would be the website, and simulate.biosimulations.org/api would be the API. This would be the same principle for the other apps.  This is trivial to set up using the google cloud load balancer that is handling the ingress for the k8s cluster. However, I have not yet been able to test a solution that would work on the uconn cluster, so I put this on the side for now.

**Comment by jonrkarr** [comment]
Paths is equally good.

**Comment by bilalshaikh42** [comment]
We can use [Biosimulations-Deployment/issues/3 ](https://github.com/biosimulations/Biosimulations-Deployment/issues/3)to make this work on cloud.  This should also work on the hpc if we switch to the nginx controller

**Comment by jonrkarr** [comment]
@bilalshaikh42 Can we rename `simulate.biosimulations.org` to `run.biosimulations.org` before COMBINE? It would be helpful to fix the major URLs before the meeting.

**Comment by bilalshaikh42** [comment]
run.biosimulations.org points to the new site. I can change the API adresses temporarily as well, but need to get an update on the HPC cluster before working on a more permanent setup

**Comment by jonrkarr** [comment]
I think the API addresses are fine for COMBINE.
