### ISSUE TITLE
Open API specification should contain enums of possible parameters

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1097]
Use the OAS spec enum rather than written examples

**Comment by gmarupilla** [comment]
@bilalshaikh42 I don't think we can do this in dispatch-api, because all the places where the API expects a string, they are dynamic values. I don't think we can hardcode anything in enums. Do you have any other  suggestion?

SO for selecting the simulator info, we already have `/api/simulators` to get all possible simulators and their versions. It's not working ever since we migrated from crbm to biosimulators docker hub repo but will be fixed when #1099 is closed.
