### ISSUE TITLE
Show CSV results dynamically on UI

### ISSUE THREAD

**Issue by gmarupilla** [reproducible-biomedical-modeling/CRBM-Viz#1102]
Every simulator generates resultant data(CSV) for the particular simulation. What if we show CSV resultant data dynamically below visualization as well in a table? Any thoughts?

**Comment by jonrkarr** [comment]
I don't think we need to display a table. I think such a table would be hard to interpret. I think we can simplify provide a link to download the results.

One alternative way to summarize the results is to display a spark line for each species such as the example below. This would give a quick visual summary of all of the predictions. I don't think this is critical to implement because (a) we already have a plotting method setup and (b) we will need to have a link to download all of the results. We have more critical things to focus on.

![image](https://user-images.githubusercontent.com/2848297/92062622-2cf6af00-ed67-11ea-9808-b00b93ee7e51.png)

**Comment by bilalshaikh42** [comment]
I believe the plotly graphs already provide this information. The mouse over shows the value of each species.
