### ISSUE TITLE
Some algorithm parameters have incorrect ids in the simulators database

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1313]
Ids should have the pattern `KISAO_000...` rather than `000...`. This is why some of the links are working (#1299).

**Comment by jonrkarr** [comment]
The BioNetGen and COPASI metadata were missing `KISAO_` prefixes. I fixed this in the `properties.json` files in the simulator container repos.

**Comment by jonrkarr** [comment]
I tried to use the simulators API to update the database. But I received this error:
```
{
  "statusCode": 409,
  "message": "Conflict",
  "error": "Database Error"
}
```

1. Used API to retrieve info about BioNetGen
2. Extracted the single record from the returned array
3. Added missing `KISAO_` prefix
4. Authenticated to API with Google credentials
5. Tried to used the POST `/simulators` endpoint to submit the single entry

**Comment by bilalshaikh42** [comment]
These have been updated. I was unable to reproduce the error you got. If a simulator with the same id/version already exists it should give you a 409. However the error should be more descriptive. 
I believe this error may have been caused by the incorrect structure for the citations as mentioned in #1311. Since that was corrected in properties.json it did not come up again.

**Comment by jonrkarr** [comment]
This is now fixed. I guess you replaced the metadata in the database.

Its hard to understand exactly what's going because the data in the databases didn't match the data model and the error message isn't informative.
