### ISSUE TITLE
Consolidate API models for Platform and Simulators

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1394]
API definitions for the platform and the simulator are defined separately. 

1) Combine the datamodels to the shared/datamodel-api library
2) Update the models API to return the new schema
3) update the database schema/methods to use the new schema and ensure that the old models can be accessed. 

Since the only current models are those that are imported from biomodels, we can update them to the new schema.  It is likely that the schema will change in the future, so it could be helpful to determine how to adapt to the api to accommodate the change and work with the newer models. 
Some approaches: 
https://derickrethans.nl/managing-schema-changes.html
https://www.mongodb.com/blog/post/building-with-patterns-the-schema-versioning-pattern
https://docs.mongodb.com/manual/tutorial/model-data-for-schema-versioning/
https://stackoverflow.com/questions/14290568/how-to-handle-mongodb-schema-change-in-production
https://stackoverflow.com/questions/60452156/managing-schema-changes-with-mongodb

**Comment by bilalshaikh42** [comment]
@lzy7071 do you have any thoughts on how to handle schema changes?

**Comment by lzy7071** [comment]
> @lzy7071 do you have any thoughts on how to handle schema changes?

I'm not too sure what you meant by handling "schema changes." 

If you meant changing and keeping track of schema version on the database side, I'm primarily using patterning and explicitly stating `schema_version` in the documents. Because my version 1.0 and version 2.0 are completely different, I'm not planning to keep version 1.0 but currently they each reside in their individual database on MongoDB. If there were going to be a v3.0, they will reside in the same database and collection as v2.0.

If you meant changes on the API side to reflect the underlying schema changes on the database side, I'm using `/v1`, `/v2`, or `/v3` to indicate the schema / API version and compatibility as I plan to keep API version in conjunction with schema version (changes to the API in between schema changes will just be `2.0.1`, `2.1.0`, etc). This way, I can also add the `schema_version` as one of the query criteria.

This is with regard to the third bullet point. If you want to keep both the old schema and the updated one in the same collection, I think when you update MongoDB schema, you would need to set the `valicationLevel` to `moderate`. But any future addition to the collection can't be of the old schema. And you'll have to use `oneOf` in the data model spec sheet.

**Comment by jonrkarr** [comment]
Regarding the current models, we can re-generate them with the revised schema. I need to update Biosimsulation_utils to reflect the revised schema anyway.

Going forward, if we change the schema, we'll want to update (migrate) the old documents to the revised schema.
- The first link you shared recommends writing a script to do this
- See also https://docs.mongodb.com/realm/ios/migrations/
- There seem to be good packages for managing migrations. Basically, the strategy is to create a script for migrating each document forward (and, optionally, backward). Then the management tool takes care of applying this to the database. The management tool can cover more complicated cases such as migrated through a series of changes. See https://www.npmjs.com/package/migrate-mongo.

I think its simpler to migrate the documents than to make the Biosimulations code support both the new and old schemas (what the links call a "schema versioning pattern"). Keeping track of the schema version used by each document is easy. However, making the biosimulations software simultaneously support multiple schema versions would complicate the software.

## Comparison to schema versioning strategy for BioSimulators
In BioSimulators, I've advocated that we take the "schema versioning pattern" approach because we won't necessarily be able to easily migrate the containers forward to a new standard. This is because the BioSimulators "version" refers both to the schema for simulator specifications and to the standard for command-line interface. The former is easy to automatically migrate. The latter could be more complicated. For example, if v2 of the command-line interface requires status output, this would take significant effort on the part of the developers of the simulation tools to implement, rather than the BioSimulators Team. As a result, changes to the simulators schema could result in the inability to continue to run older containers (unless the team that maintains them migrates them forward).

On way to increase our ability to handle this would be to distinguish
- the version of the simulator specifications schema
- the version of the command-line interface standard
- (the version of the docker container structure -- at least for now, I think this can be lumped with the version the command-line interface standard)

## Handling versions of modeling formats
While we're on the topic of versions, BioSimulations is also sensitive to different versions of the model formats, SED-ML, and COMBINE. 
- I don't think we need to worry about changes to the model formats much because support for different versions of each model format is delegated to the containers. 
- If SED-ML changes, we'd want to update Biosimulations_utils to the new version. I don't think this will have much impact on the containers because we're only using a subset of SED-ML which I think is stable. The new developments in SED-ML mainly overlap with Vega. We are planning to use Vega instead. For that reason, I don't think the new developments in SED-ML will be a challenge for us.
- I think the Vega viewer is capable of rendering old versions of the Vega schema.
- If COMBINE/OMEX changes, we'd want to update Biosimulations_utils to the new version. This shouldn't impact the containers because the containers rely on a subset of COMBINE/OMEX which I don't think will change.

**Comment by bilalshaikh42** [comment]
This can be updated/reopened once we redesign the platform
