### ISSUE TITLE
Enable URL navigation for tabs in resource views

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1438]
Sharing a URL to a view page for a resource does not preserve the user tab.There should be a parameter to save the tab currently in use.

current URL : https://biosimulators.org/simulators/amici/latest

proposed URL: https://biosimulators.org/simulators/amici/latest?tab=3

**Comment by jonrkarr** [comment]
Tab ids would be more meaningful to users (e.g., `versions` instead of `3`).

I usually see this done using hashes e.g., `https://biosimulators.org/simulators/amici/latest#versions`.

Another alternative is to use [`mat-tab-nav-bar`](https://material.angular.io/components/tabs/overview). This would turn each tab into a separate route. This would require more refactoring.

**Comment by jonrkarr** [comment]
Added an optional `urlHashFragment` attribute to `TabPageTabComponent`. This enables navigation to particular tabs, e.g. https://biosimulators.org/simulators/tellurium/latest#versions. The hash is in the address bar is now automatically changed when the user navigates to a tab that has a defined hash.
