### ISSUE TITLE
Data table does not fit all feilds when multiple columns are added

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#144]
Still seeing it. Only slightly off with the sidebar closed but for so with it open.

![image](https://user-images.githubusercontent.com/32490144/68640740-b71f0f80-04d6-11ea-9125-e4a29e00e919.png)

![image](https://user-images.githubusercontent.com/32490144/68640853-0107f580-04d7-11ea-88b4-117cf3f32abc.png)

_Originally posted by @bilalshaikh42 in https://github.com/reproducible-biomedical-modeling/CRBM-Viz/pull/132#issuecomment-552724052_

**Comment by jonrkarr** [comment]
Although the table can display all of the columns at once, the design is optimized for a few columns rather than all at once.

All of the fields are shown, and the columns are equal width. The way to see the full content of each column is to turn horizontal scrolling on. I've turned this off because I don't horizontal scrolling. Its a nice feature for Excel when you're trying to analyze a data set, but I think it clutters a UI which tries to provide a quick overview of a list of models or simulators.

**Comment by jonrkarr** [comment]
I'm implemented the third option in b4cc8935dd3bc3718865be055da9ab710d3c39f0. Is this what you had in mind?

**Comment by bilalshaikh42** [comment]
> I'm implemented the third option in [b4cc893](https://github.com/reproducible-biomedical-modeling/CRBM-Viz/commit/b4cc8935dd3bc3718865be055da9ab710d3c39f0). Is this what you had in mind?

Yup, this works well
