### ISSUE TITLE
Organize dispatch api using REST semantics

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1480]
The dispatch API routes should be organized to follow rest semantics. Users should put a  simulation run, and get back simulation runs with data/status.

**Comment by bilalshaikh42** [comment]
Simulators should be represented as a resource. 
/Simulators endpoint should not return different outputs based on query

**Comment by gmarupilla** [comment]
> Simulators should be represented as a resource.
> /Simulators endpoint should not return different outputs based on query

Yes, I too had that in mind. This API is temporary and might not even be working anymore ever since we moved the docker images from the Docker registry to the GitHub registry. So, this will eventually be removed once the simulators API (api.biosimulators.org) is ready (has all the simulators and their versions) and that will be a server to server request therefore we won't need this API.

I tried adding more simulators using the post request in BioSimulators API, it was asking for a lot of other info that I wasn't sure what to write. To bypass the validations, I can directly do that from mongo DB. Should I go ahead and do that for #1263 ?

**Comment by gmarupilla** [comment]
> The dispatch API routes should be organized to follow rest semantics. Users should put a simulation run, and get back simulation runs with data/status.

These are the mappings that I'm considering:

POST /dispatch -> POST /simulation-run

GET /download/{uuid} -> GET /simulation-run/download/{uuid}

GET /logs/{uuid} -> GET /simulation-run/logs/{uuid}

GET /result/structure/{uuid} -> GET /simulation-run/structure/{uuid}

GET /result/{uuid} -> GET /simulation-run/{uuid}


POST /jobinfo -> We can keep it as is, even though it fetches the data but according to the REST semantics, it is a search, it CREATES a search at the backend and it is considered valid to create a search using POST request.

**Comment by bilalshaikh42** [comment]
Addressed in #1484
