### ISSUE TITLE
Dispatch API/Service share Database connection

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1482]
Both the dispatch and the service are connecting to the database. This is probably not the best design option. Communication between the API and service should be through messages, not the database.

**Comment by gmarupilla** [comment]
Agreed. But, things like job status, simulation status and results are required by frontend, so in this scenario, we need to have a DB connection with API. Now, service is accessing DB to check and update job status, since service is the only part which can interact with HPC, only service will have the info about job updates, so you need me to create a message subscriber (@MessagePattern) in API and then store the job status updates received from service (via MQ) into DB through API. Is that right?
