### ISSUE TITLE
Unable to resolve EDAM format_3972

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1486]
The simulators app isn't resolving EDAM `format_3972` (BGNL). Example: second row of table in https://biosimulators.org/simulators.

`format_3972` is defined in `libs/ontology/sources/src/lib/edam.json`. My best guess is that the deployed API is using an old version of `edam.json` which doesn't have this term. @bilalshaikh42 could you check if this needs to be updated?

**Comment by bilalshaikh42** [comment]
Yes I can redeploy the API. What happened is that the changes to the ontology script in a previous commit changed the url for the owl file. That url contains an out of date file.
This was fixed in https://github.com/biosimulations/Biosimulations/pull/1467/commits/c2805d10f9e8313bc7b891ff0882ba38733b7f77 as a part of #1467.

**Comment by bilalshaikh42** [comment]
I am now seeing this resolved at https://biosimulators.org/simulators. 
Might be a couple minutes until the cache clears.
