### ISSUE TITLE
Simulation fails for unknown reasons, unrelated to simulators

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1799]
- Simulation id: 5fdfae6ca2f1af479ae5c30a, [OMEX file](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Parmar-BMC-Syst-Biol-2017-iron-distribution.omex)
- Simulation id: 5fdfadc5a2f1af748fe5c302, [OMEX file](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Caravagna-J-Theor-Biol-2010-tumor-suppressive-oscillations.omex)

**Comment by jonrkarr** [comment]
I don't think its related to VCell. I ran the simulation again with VCell, and it succeeded.

**Comment by bilalshaikh42** [comment]
Both jobs ran successfully on the HPC. If they were marked as failed, this was because the service was unable to connect to the hpc and get the updated status, and thus defaulted to failed to handle the error. The new host for the hpc should help with this as well, and I can create a new issue to handle ssh timeouts a little more robustly. 
This is likely tied to #1712
