### ISSUE TITLE
Restore viz column in simulations table | make API return enough information for table to know whether there is data that can be visualized

### ISSUE THREAD

**Issue by moraru** [reproducible-biomedical-modeling/CRBM-Viz#1810]
The viz column disappeared completely and clicking on any of the actual runs has the viz part grayed out, even for the runs that do have CSV results.

**Comment by jonrkarr** [comment]
This is already discussed in #1797. The Viz column was intentionally removed because the API doesn't provide enough information to know whether there are results are not. The API only says whether there was an output (report OR plot), whereas viz requires at least one report.

The visualization is still working. You may need to refresh your browser. If you still see the error, please post a specific description of how to reproduce the error.

**Comment by moraru** [comment]
Hard refresh of the browser worked, design chart tab is no longer grayed out on the runs that do have results.

However, it seems that the simulations detail page is able to distinguish on a successful run whether it has CSV output (tab available) vs PDF output (tab greyed out) - shouldn't it be possible then to use the same logic to populate the viz links column?

**Comment by jonrkarr** [comment]
Yes, the simulations table component needs to subscribe to another endpoint which has this information, as the view simulation component is doing. I haven't had time to do this yet. I've been working to make sure 5 simulation tools are working with examples for each.

**Comment by bilalshaikh42** [comment]
can this be closed?

**Comment by jonrkarr** [comment]
Ideally, the column of "Viz" buttons should be restored to the simulations tables. Unless @bilalshaikh42 just took care of this, I think the column is still commented out.

**Comment by jonrkarr** [comment]
I added back the viz button in #2267. The summary table still isn't using the results endpoint to detect if data is available to visualize. Instead, the "Design viz" tab is now always enabled; when no report is available, it displays a message that says no data is available rather than displaying the visualization design form.
