### ISSUE TITLE
Dispatch app is not saving simulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1882]
run.biosimulations.org is not saving submitted simulations to local storage. This may be a local browser issue, but I believe it is a problem with the app

**Comment by bilalshaikh42** [comment]
Unable to reproduce

**Comment by bilalshaikh42** [comment]
The current production deployment does not seem to have the issue, but I am encountering in the dev deployment

**Comment by bilalshaikh42** [comment]
I think I see the issue now. The app at the dev deployment is not running in production mode. There must be some limitations to the storage when this is the case.

**Comment by bilalshaikh42** [comment]
That was not sufficient to fix the issue. @jonrkarr Could you take a look? This is going to block other changes since I need the dev deployment to test any changes

**Comment by jonrkarr** [comment]
My initial thought is that maybe there's a security setting we need to set.

Second, it sounds like the `dev` deployment should be changed to run in production mode.

**Comment by jonrkarr** [comment]
The status will be polled while either of these conditions are true:
- The status of a simulation is `CREATED`, `QUEUED`, or `RUNNING`
- The status of a simulation `SUCCEEDED` and `resultsSize` is `undefined`

(a) The `resultsSize` attribute is undefined for the previously run "example" simulations. This will cause the polling for status to repeat forever. The "example" simulations need to be re-run. @bilalshaikh42 do you see this problem when "your simulations" only includes simulations that you've run recently?

(b) The reason that the polling checks for `resultsSize` is that it needs `resultsSize` to determine whether to display a download button. It look like the `resultsSize` is updated after status is set to SUCCEEDED. @bilalshaikh42 is that correct?

**Comment by jonrkarr** [comment]
I updated the example simulations. On my browser, the app doesn't continue to poll status with these simulations.

**Comment by jonrkarr** [comment]
I can confirm this is specific to `production` mode. 

I don't think this is related to the IndexedDB. Other methods are able to set and read that.

This seems to result from a difference in how `production` vs `development` is compiled.

**Comment by jonrkarr** [comment]
Actually, I can replicate this in development as well.

**Comment by bilalshaikh42** [comment]
Yes, I i initially thought it had to do with production mode, but that does not seem to be the issue. 

Using logging statements it seems that the storage module is not initializing. The "ready" event never fires.

**Comment by jonrkarr** [comment]
The ready event fires in my browser. I think the issue is with the `keys` method. Shouldn't take much longer to figure this out.

**Comment by jonrkarr** [comment]
It works for me in firefox.

**Comment by bilalshaikh42** [comment]
This is strange. I am now able to get it to work in chrome as well.

**Comment by bilalshaikh42** [comment]
It seems the issue is completely  resolved on run.biosimulations.dev for me now. But there has not been any changes to the deployment since I last could reproduce the issue yesterday. I performed the same clearing of the browser cache yesterday, though I did restart the browser completely because I was running into issues loading other websites as well.  I would have assumed that meant it was unique to my browser, but it seems you were also able to reproduce it?

**Comment by jonrkarr** [comment]
I thought I understand what's happening, but now I don't think so. I see the problem in Chrome, but not in Firefox. In Chrome, the promise for the `ready` method resolves, but the promise for the `keys` method doesn't (neither does the `get` method). Executing the `set` method doesn't translate into the IndexedDB initializing. No errors appear to be thrown either. The issue seems to be specific to Chrome, likely a change in a recent version. I'll probably try installing an older version from the Fall.

**Comment by jonrkarr** [comment]
I cleared my whole Chrome cache (all apps) and it seems to work now.

**Comment by jonrkarr** [comment]
Its working for me in all of these environments:
| Branch | Browser | OS |
| ------- | --------- | ---- |
| deploy | Chrome | Windows |
| deploy | Edge | Windows |
| deploy | FireFox | Linux |
| deploy | FireFox | Windows |
| karr/dev | Chrome | Linux |
| karr/dev | FireFox | Linux |
| dev | Edge | Windows |
| dev | Chrome | Linux |
| dev | Chrome | Windows |
| dev | FireFox | Linux |
| dev | FireFox | Windows |

I noticed one exception. deploy on Chrome on Linux uses WebSQL rather than IndexedDB. I think this might be the origin of the issue. ionic/storage is supposed to provide abstraction over the underlying storage. But, it seems that isn't quite happening. I need to explore a bit more.

**Comment by jonrkarr** [comment]
When I run the locally in `production` mode, Chrome uses IndexedDB. I'm trying to figure out two things (a) why chrome is sometimes using WebSQL and (b) why WebSQL isn't working.

**Comment by jonrkarr** [comment]
(a) I fixed an issue with WebSQL so that simulation storage should work when the ionic storage falls back to use WebSQL. I don't think this addresses the problem I'm seeing in deployment in Chrome in Linux.

(b) The new deployment of run.biosimulations.org seems to be working better, although its using WebSQL in Chrome/Linux for reasons I don't understand. The fix I mentioned above should address the remaining issue.

(c) I don't know why run.biosimulations.org is using WebSQL. I can't figure out how to reproduce this locally. I tried compiling and running the deploy branch in various ways locally. None lead to the app using WebSQL.

**Comment by jonrkarr** [comment]
# READ THIS SUMMARY
I think we should do this:
- Deploy #1894 to run.biosimulations.org. I think this will address the latest issue I'm seeing in the deployed app.
- Try run.biosimulations.org and assess if any further issues need to be addressed. I can't replicate the remaining issues, so I think we need to deploy the new changes and see what happens.

**Comment by bilalshaikh42** [comment]
This seems to be resolved
