### ISSUE TITLE
Create testing for Simulator API

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1890]
We dont have any end to end testing of the simulators api. 
We should create a series of expected responses to inputs for the api and use a tool like [Postman](https://www.postman.com/automated-testing/) to prevent regressions. 

In the meantime, @jonrkarr Could you confirm that the validation is still working on the simulators api? I remember there was some issue regarding null vs undefined. I had to make some changes to the code because of updated types, so want to make sure that is still working.

**Comment by jonrkarr** [comment]
For testing the API, use the same [COMBINE archives as the simulators test suite](https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/examples). The test suite will have already checked that the simulation tools can execute those archives. The README has a table of which tools should be expected to work with which COMBINE archives.

Since the simulators are tested separately, I recommend using just a couple of simulators to test the API. You could do nearly all of the testing with just 1 simulator (e.g., COPASI). And then include a couple of additional tests with other simulators just to make sure that the successes aren't unique to the particular simulator you chose to do the majority of the testing with.

**Comment by jonrkarr** [comment]
Which version of the simulators API needs to be checked?

**Comment by jonrkarr** [comment]
The simulators API looks fine. 

I curated the new attributes for all of the simulation tools and pushed them to the deployment API. 

The specs for all of the simulation tools are valid with (a) the deployed production API, (b) the deployed dev API, and (c) the dev branch.

I also manually checked a few things:
- `Person.middleName`
  - optional. when not submitted, the value becomes `null`
  - `null` value is preserved
- `Simulator.algorithms` 
   - attribute is required
   - `null` is not a valid value
- `Algorithm.parameters` 
  - attribute is required
  - `null` value is preserved rather than replaced with `[]`

Ideally, we would have unit tests so we could be more confident. Maybe what we really want to do is abstract out our null handling for mongoose into our own decorator, which in turn calls the mongoose decorator. If we reused this, we'd only have 1 method we'd need to test.

**Comment by jonrkarr** [comment]
Closing. Discussion of needed testing is in #2656.
