### ISSUE TITLE
Remove logging of results

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1943]
On completion of the simulation, results should not be logged. This clutters the logs making it harder to debug

**Comment by jonrkarr** [comment]
For debugging, I think its useful for us to have a comprehensive log that encompasses everything that the SLURM job does. I think this can also be helpful for users because it transparently communicates exactly what each SLURM job did. Personally, I like this feature of services such as GitHub actions and Read the Docs.

#1851 is intended to allow simulators to provide more helpful, more structured logs for users. Since these logs won't cover 100% of each SLURM job, I think we should also make it possible for users see the comprehensive log. A think a link to download it would be fine.

The remaining case is when simulators don't support the kind of log discussed in #1851. In this case, I think it would be sufficient to display the comprehensive log. I don't think we need to work too hard to clean this up for users since that's the goal of #1851.

**Comment by bilalshaikh42** [comment]
This is just for me to remember to remove some of the logging statements
that  I had added
Currently, the results array is printed out and this clogs up the logs when
trying to debug a specific run.
These logs are not visible to users, but stored on google cloud

**Comment by bilalshaikh42** [comment]
This was an easy fix, already done in #1944. Just waiting to merge in #1931  first

**Comment by jonrkarr** [comment]
I'm working on expanding the logs that the simulators produce.
