### ISSUE TITLE
Log Parsing is failing on the front end 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2046]
**Please describe the bug**
The front end is not displaying the structured logs correctly

**Please describe how to reproduce the bug**
1. Go to https://run.biosimulations.dev/simulations/601089bcc4eb1ef2c987f3fd#tab=log

**How should BioSimulations have behaved**
Logs should be displayed with color and should show correct output. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/32490144/105909689-e47dad80-5ff5-11eb-93bc-15ff001cdbbf.PNG)

**Additional context**
Error source "valie" is undefined
```
    if ('simulatorDetails' in value && value?.simulatorDetails?.length) {
      this.formattedSimulatorDetails = value.simulatorDetails.map(
        (keyValue: SimulatorDetail): FormattedSimulatorDetail => {
          const key = keyValue.key;
          const value = keyValue.value;
          return {
            key: key,
            value: typeof value === 'object' ? JSON.stringify(value, null, 2) : value.toString()
          };
        }
      );
    }
```

**Comment by bilalshaikh42** [comment]
Here is the api response that is causing the error. It seem that the simulator details contains a key for "parameters" that does not have an associated value. Since the rest of the response is valid, this must be caused by the image output. 

I can make a patch to the front end to handle this case, but it seems like the value should be reported as null

Relevant Section: 
```
           "simulatorDetails": [
            { "key": "methodName", "value": "deterministic" },
            { "key": "methodCode", "value": 22 },
            { "key": "parameters" }
          ],
```
Full Response: 
```{
  "duration": 0.37655,
  "exception": null,
  "output": null,
  "sedDocuments": [
    {
      "duration": 0.281335,
      "exception": null,
      "location": "LSODA.sedml",
      "output": "Found 1 SED-ML documents with 1 models, 1 simulations, 1 tasks, 1 reports, and 0 plots:\r\n  LSODA.sedml:\r\n    Tasks (1):\r\n      task1\r\n    Reports (1):\r\n      report_1_task1: 2 data sets\r\n\r\nExecuting SED-ML file 0: LSODA.sedml ...\r\n  Found 1 tasks and 1 outputs:\r\n    Tasks:\r\n      `task1`\r\n    Outputs:\r\n      `report_1_task1`\r\n  Executing task 1: `task1`\r\n    Executing simulation ... \u001b[34msucceeded\u001b[0m\r\n    Generating 1 outputs ...\r\n      Generating output 1: `report_1_task1` ...",
      "outputs": [
        {
          "dataSets": [
            { "id": "time", "status": "SUCCEEDED" },
            { "id": "pmTORC1", "status": "SUCCEEDED" }
          ],
          "duration": 0.100731,
          "exception": null,
          "id": "report_1_task1",
          "output": "",
          "skipReason": null,
          "status": "SUCCEEDED"
        }
      ],
      "skipReason": null,
      "status": "SUCCEEDED",
      "tasks": [
        {
          "algorithm": "KISAO_0000560",
          "duration": 0.116445,
          "exception": null,
          "id": "task1",
          "output": "",
          "simulatorDetails": [
            { "key": "methodName", "value": "deterministic" },
            { "key": "methodCode", "value": 22 },
            { "key": "parameters" }
          ],
          "skipReason": null,
          "status": "SUCCEEDED"
        }
      ]
    }
  ],
  "skipReason": null,
  "status": "SUCCEEDED"
}
```

**Comment by jonrkarr** [comment]
The issue appears to be with the log API. 

The image is producing the `value` attribute with value equal to `{}`:
```yaml
simulatorDetails:
 - key: methodName
   value: deterministic
 - key: methodCode
   value: 22
 - key: parameters
   value: {}
```

It looks like the log API is dropping the `value` attribute, probably because the data type doesn't match what it expects.

In any case, I made the frontend more resilient so that it will produce the empty string when `value` is missing.

**Comment by jonrkarr** [comment]
Sounds to me that the mongoose decorator for the value attribute needs to be corrected.

As a first step, take a look at what was input to the API after the simulation run. The yaml should show `value: {}`. I assume the YAML file will be parsed correctly. Assuming the YAML is parsed correctly, then check that what the database stores is the same as what it received -- I think the two are different, likely because of a minor issue with our use of Mongoose.

**Comment by bilalshaikh42** [comment]
This seems to be a similar issue.  
https://stackoverflow.com/questions/26703742/mongoose-is-removing-empty-object-out-of-embedded-documents-in-array

**Comment by jonrkarr** [comment]
Unfortunately, more complicated than I estimated. But the post suggests a solution.

If that solution doesn't work, we could (a) change the simulators to produce `null` instead of `{}` and (b) add custom validation to check that the value isn't `{}`.

**Comment by bilalshaikh42** [comment]
Was just as simple as disabling the minimization.

**Comment by bilalshaikh42** [comment]
Run run simulations 
https://run.biosimulations.dev/simulations/6010a2cffcf6c0bb97bfc8ba#tab=log

**Comment by jonrkarr** [comment]
Looks good!

The logging is structured so that the collected output should be minimal, unless there's an error. As a result, most or all of our examples won't demonstrate the collection of ANSI codes for colors/bold/underlining. I think we'd need to create an example that codes for a failing simulation to demonstrate these codes and their rendering.
