### ISSUE TITLE
Logs do not appear for failed simulation runs

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2051]
If a simulation fails, the log processing is never called. This causes the database entry for the log to be empty. The api  corrects for this by attempting to read the output from the filesystem, but it seems that that is failing as well, leading to the final output being an error message.  This is probably because the output std err file is now combined with the std out

quick fix- have the error handling method read the correct file 

Solution- run the log processing on the failure event as well as the success event (this is obvious in hindsight, but I forgot to account for it)

**Comment by jonrkarr** [comment]
The simulation tools are designed to generate `log.yml` even if one or more tasks or outputs fails. 

The simulation tools are also designed to output to `log.yml` "progressively" so that a partial log should be available even if the SLURM job fails, such as because the SLURM job times out or runs out of memory. In such cases, `log.yml` will be syntactically valid. It will include all SED documents, tasks, and outputs. The status of the documents, tasks, and outputs that hadn't yet been run by the time of the failure will be QUEUED and their output and exception attributes will be `null`.
