### ISSUE TITLE
Replace SSH polling implementation

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2119]
Currently, the ssh polling is done locally per instance of the dispatch-service. This leads to the service having a state that is lost if the service crashes (caused by bugs) or restarts ( caused by updates). This leads simulation runs to stop updating in their last recorded state. 

Another problem that is caused by this approach is that the service makes many requests to the hpc cluster at the exact same time due to the cron jobs syncing up. 

Both these issues can be solved by using a queue that is shared between the dispatch-service instances.  NestJS provides a wrapper for queues that would simplify much of the set up. https://docs.nestjs.com/techniques/queues
The kubernetes cluster has a redis-cluster already available. 

A potential starting point would be to have the dispatch-api add new simulationRuns to a queue. The service can then consume these. This would solve many of the reliability issues we have been having. The dispatch service would then be able to add a [repeating job](https://optimalbits.github.io/bull/) to a monitoring queue. Finally, on completion, a third queue would handle the processing of the results and logs. 

@gmarupilla  Would you be interested in getting started on this?

**Comment by gmarupilla** [comment]
Yes, I'll work on this. 
I understood the part where we will add the jobs to the queue, and I also understood who will consume the jobs from the queue, but what I couldn't understand was, how will it prevent/replace the SSH polling? Because, whenever a job is consumed(listened to) from the Redis queue, in the end, we will have to SSH HPC to check the job status with SLURM ID, correct? or Am I missing something?

**Comment by bilalshaikh42** [comment]
Done
