### ISSUE TITLE
Default routes for "your" components

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#214]
Currently "/users/username/" leads to a user's profile. "/user/" leads to the logged in users profile. 
This is expected and intended design. 

However, I am not sure that this pattern should carry over into other paths. For example while "models/username" should lead to a users models, "/models/" should not redirect to the currently logged in users models as 

1) This causes an account to be required for essentially the whole "/models" sub routes
2) Is counter intuitive for those who go to "/models" to browse for models, not to look at their own

I can rewrite these components to instead use some path such as "/models/?user=username". The "/models" path would lead to the "browse" functionality, while clicking on "your models" would automatically redirect to "models/?user=username" where the username is the username of the currently logged in user.

_Originally posted by @bilalshaikh42 in https://github.com/reproducible-biomedical-modeling/CRBM-Viz/pull/201#issuecomment-563071516_

**Comment by bilalshaikh42** [comment]
related to  #168

**Comment by jonrkarr** [comment]
`/models/` is intended to display all models, not just those owned by the logged in user. A user account is only intended to be needed to upload a new model or edit an existing model.

`/user/models` is intended to display the models owned by the current user
`/user/:id/models` is intended to display the models owned by an arbitrary user

Because the models grid is a shared component, this URL organization doesn't require bringing the functionality of the models module into the user module.

If you prefer the URL patterns `/models/manager` and `/models/:userId`, that's fine with me. The former could display the models owned by the loggedIn user. This avoids putting the logged in user's username in the URL.

For these paths that display a user's resources, I think its nice to encode the user's name into the URL path rather than into query arguments. I think this makes users feel like they have a dedicated page to advertise their resources.

**Comment by bilalshaikh42** [comment]
Oh, I see now. 
I had assumed based on the breadcrumbs that the the page itself would display "your models" rather than provide a link to the page.
 
The current setup works well.

**Comment by jonrkarr** [comment]
In case its not clear, the other modules are setup the same way.

The routes that have AuthGuard indicate where a user account is needed. I needed to change this to be applied at the route level rather than at the module level.
