### ISSUE TITLE
Replace lunr with  flexsearch

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2184]
The table/dispatch component are quite large (almost 5mb). Part of this is because lunr is not optimized with es6 module imports. This can be replaced by [flexsearch](https://github.com/nextapps-de/flexsearch) which seems to be faster, more lightweight, and should support webworkers in an upcoming release.

**Comment by jonrkarr** [comment]
I looked into FlexSearch and some other potential alternatives. The only other potentially usable library was elasticlunr, but this is inactive.

I explored replacing Lunr with FlexSearch in #2271. For the most part, FlexSearch is easy to use in place of Lunr. 

However, in my opinion FlexSearch lacks a key feature of Lunr. Lunr supports searching over individual fields, wildcards, and negation. See https://lunrjs.com/guides/searching.html. This isn't trivial to add on top of FlexSearch. FlexSearch provides something which looks like it could be used to search over individual fields and apply negation. However, this doesn't work. This might be because its a new feature that's described in the documentation that hasn't been released yet.

I don't have a strong opinion about the relative benefit of speed/size vs more search capabilities. If you have a preference, the flexsearch PR #2271 can be merged in.

**Comment by jonrkarr** [comment]
Closing because FlexSearch lacks a key feature. Can be reopened if someone feels strongly about this issue.
