### ISSUE TITLE
Make the resources allocated to each simulation job configurable

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2347]
This is in response to reviewer feedback.

Currently, jobs are limited to 1 core, 8 GB, and 20 min.

20 min seems low. @moraru can we increase this to say 12 h?

**Comment by moraru** [comment]
This is some blatant error or misunderstanding – regular jobs are capped at a wallclock time of 20 *days*, not *minutes*… Not sure where this comes from.  And, BTW, the limit can be overridden – for VCell, we have a special “power user” setting which allows jobs to run for 21 days or longer, which we can also configure for biosimulations if necessary, but it obviously never came into play, since no job ever came close to that limit (and probably will never do until we run spatial simulations).

From: Jonathan Karr ***@***.***>
Sent: Tuesday, March 30, 2021 12:36 AM
To: biosimulations/Biosimulations ***@***.***>
Cc: Moraru,Ion ***@***.***>; Mention ***@***.***>
Subject: [biosimulations/Biosimulations] Increase resources allocated to each simulation job (#2347)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

This is in response to reviewer feedback.

Currently, jobs are limited to 1 core, 8 GB, and 20 min.

20 min seems low. @moraru<https://urldefense.com/v3/__https:/github.com/moraru__;!!N0rdg9Wr!82qx6zFZzOEBOc7oVwbD0Ug1zwQaNc-nkXbi1fIaoE0-3aCvwSCPBI4SCGoaEg$> can we increase this to say 12 h?

**Comment by jonrkarr** [comment]
I believe Bilal is setting the SBATCH jobs much more conservatively. We're
going to change this.

**Comment by bilalshaikh42** [comment]
Sorry for the confusion. I simply set the limit to 20 minutes, since I wanted jobs to time out beyond that while testing. This can be much greater.

**Comment by jonrkarr** [comment]
- [x] Add options to GUI
    - Default options should be higher than present values
    - Maxima:  24 cores, 192 GB RAM, and 20 days
- [x] Add options to REST API
   - Validation should enforce our chosen maxima: 24 cores, 192 GB RAM, and 20 days
- [x] Apply options to SBATCH script

**Comment by jonrkarr** [comment]
Ready to test and deploy
