### ISSUE TITLE
Document total resources available and resources available to each job

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2348]
@moraru, @mpw6  what is the total amount of resources available to the dispatch app (or could be allocated, potentially even just temporarily)?
- Cores
- RAM
- Disk space

I started slots for this information in the FAQ (`biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html`) in a new branch.

**Comment by moraru** [comment]
That is a loaded question.  Since biosim is running in the general pool, jobs can *potentially* use up to the entire amount of non-reserved resources (thousands of cores, TBs of RAM, and PBs of storage).  Obviously not the proper answer, need some thinking about how to address.

From: Jonathan Karr ***@***.***>
Sent: Tuesday, March 30, 2021 12:39 AM
To: biosimulations/Biosimulations ***@***.***>
Cc: Moraru,Ion ***@***.***>; Mention ***@***.***>
Subject: [biosimulations/Biosimulations] Document total resources available and resources available to each job (#2348)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

@moraru<https://urldefense.com/v3/__https:/github.com/moraru__;!!N0rdg9Wr!_mZAY44QAY6VuHJHu6izgak2j-4rC61Ak3GAgPSOKpuZh8F80AmB0HlJ1bNRXw$>, @mpw6<https://urldefense.com/v3/__https:/github.com/mpw6__;!!N0rdg9Wr!_mZAY44QAY6VuHJHu6izgak2j-4rC61Ak3GAgPSOKpuZh8F80AmB0HmndT26ww$> what is the total amount of resources available to the dispatch app (or could be allocated, potentially even just temporarily)?

  *   Cores
  *   RAM
  *   Disk space

I started slots for this information in the FAQ (biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html) in a new branch.

**Comment by jonrkarr** [comment]
This what I'm thinking of responding with and posting to the FAQ:
> Currently, RunBioSimulations has access to over 50 TFLOPs from 2,168 cores, 11 TB RAM, and 8 PB storage. Of this, 48 cores and 384 GB RAM are currently dedicated to RunBioSimulations. This dedicated allocation is easily configurable and can easily be expanded as user demand grows. The additional cores and RAM are shared with other users of the HPC system at UConn Health. This sharing is managed using SLURM.
