### ISSUE TITLE
Results cannot handle special characters in keys.

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2440]
This has supposedly been resolved in later versions of mongo, but might need to set some options on the drivers.

[Some discussions on workarounds
](https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name)

**Comment by jonrkarr** [comment]
The [MongoDB docs](https://docs.mongodb.com/manual/core/document/) say
- The database engine supports "." and "$" as of v3.6
- The query language doesn't support "." and "$"

The [Moongoose issues](https://github.com/Automattic/mongoose/issues/7470) also appear to suggest that "." isn't yet supported.

In practice, it sounds like  "." and "$" can't be used and they need to be avoided. As long as we avoid dictionaries that involve user-contributed keys, we should be fine.

(Keys equal to the ids of SED-ML objects would also be ok because SED-ML ids have to start with a letter or underscore and can only contain letters, numbers, and underscores. But, I think we've agreed that the database should never use user-contributed keys.)
