### ISSUE TITLE
Simulation results storage appears to be failing

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2459]
Examples with tellurium:
- http://localhost:4200/simulations/6079067de1002d931719ecd2#tab=log
- https://run.biosimulations.dev/simulations/607906b7e1002d562919ecd9#tab=log

**Comment by bilalshaikh42** [comment]
Here are the relevant logs: 
Dispatch Service: 
```
[Nest] 1   - 04/16/2021, 3:38:42 AM   [ResultsService] Failed to upload report simulation_1.sedml%2Freport for simulation 607906b7e1002d562919ecd9 +28ms
[Nest] 1   - 04/16/2021, 3:38:42 AM   [ResultsService] Error: Request failed with status code 400 +1ms
[Nest] 1   - 04/16/2021, 3:38:42 AM   [ResultsService] Failed to upload all results +1ms
[Nest] 1   - 04/16/2021, 3:38:42 AM   [ResultsService] Error: Request failed with status code 400 +1ms
```

Dispatch API:
```
[Nest] 1   - 04/16/2021, 3:38:42 AM   [BiosimulationsExceptionFilter] BiosimulationsError: Parse Error +539ms
[Nest] 1   - 04/16/2021, 3:38:42 AM   [BiosimulationsExceptionFilter] Object:
{
  "error": [
    {
      "status": "400",
      "title": "Parse Error",
      "detail": "Inconsistent datatypes for key ",
      "source": {
        "pointer": "/\"Phosphorylated"
      },
      "meta": {
        "time": 1618544322013,
        "url": "/results/607906b7e1002d562919ecd9/simulation_1.sedml%2Freport"
      }
    }
  ]
}

```

The Parse error happens when a dataset contains a mix of datatypes. I.e booleans mixed with floats. 
[Here](https://github.com/biosimulations/Biosimulations/blob/0bcec6470884845b5e79a151c696756af00aa1f8/biosimulations/apps/dispatch-api/src/results/results.controller.ts#L106) is the code that raised the error 
```
if (firstValue == 'true' || firstValue == 'false') {
        const newArr = arr.map((value) => {
          value = String(value).toLowerCase().trim();
          if (value != 'true' && value != 'false') {
            throw new BiosimulationsException(
              HttpStatus.BAD_REQUEST,
              'Parse Error',
              `Inconsistent datatypes for key `,
              undefined,
              undefined,
              `/${key}`,
            );
          }
          return Boolean(value);
        });
        report[key] = newArr;
      } else {
        const newArr = arr.map((value) => {
          const num = Number(value);
          if (isNaN(num)) {
            throw new BiosimulationsException(
              HttpStatus.BAD_REQUEST,
              'Parse Error',
              `Inconsistent datatypes for key `,
              undefined,
              undefined,
              `/${key}`,
            );
          }
          return num;
        });
        report[key] = newArr;
      }
    }
        });
```

EDIT: Its not the Boolean cast but the Number cast that must be failing.
Looking at the h5 file, there are no boolean string. So the problem must be that one of the numbers is not parsed properly. To debug further, I can modify the code above to print out the value causing the issue. Perhaps one of the numbers is out of range?

I've attached the full output here
[607906b7e1002d562919ecd9.zip](https://github.com/biosimulations/Biosimulations/files/6322610/607906b7e1002d562919ecd9.zip)

**Comment by bilalshaikh42** [comment]
I see the problem. There is no field called ""Phosphorylated". However, there is  "Phosphorylated,  modified Swe1", and other such fields. The data is being read from csv output. The first comma in the header is causing the issue. "modified Swe1" cannot be parsed into a number, causing the issue. 

This should be addressed by  parsing the HDF rather than the csv I imagine. But until  then, we can fix it on  either the simulators or the service side.

**Comment by jonrkarr** [comment]
It may be because one of the rows begins with `"Phosphorylated, modified Swe1"` (enclosed in double quotes due to a comma inside the row label). csv2json's docs suggest it should be able to handle this. Maybe its not handling this.

Can you also check that csv2json works with unicode characters (e.g., `TNFα`)?

**Comment by bilalshaikh42** [comment]
[Here ](https://github.com/biosimulations/Biosimulations/blob/0bcec6470884845b5e79a151c696756af00aa1f8/biosimulations/apps/dispatch-service/src/app/results/results.service.ts#L98) is the parsing code causing the error, in particular line 98. It is simply splitting on "," without accounting for any quotes. 

```
  private async readCSV(file: string): Promise<SimulationRunReportDataStrings> {
    // info https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line

    try {
      const rlp = readline.createInterface({
        terminal: false,
        input: fs.createReadStream(file),
        crlfDelay: Infinity,
      });
      const resultObject: SimulationRunReportDataStrings = {};

      for await (const line of rlp) {
        const header = line.split(',')[0];
        resultObject[header] = [];
        const values = line.split(',').slice(1);
        values.forEach((value) => resultObject[header].push(value));
      }
```

**Comment by jonrkarr** [comment]
The CSV files are valid CSV. Elsewhere you're using csv2json. This can handle the splitting correctly. Use csv2json at line 98 instead.

`import csv from 'csvtojson';`

**Comment by bilalshaikh42** [comment]
If  I remember correctly, the reason this is done manually was because csvtojson was assuming a different orientation than was output. I'll look into working around that.

This is the same issue that I ran into  https://github.com/Keyang/node-csvtojson/issues/381

**Comment by jonrkarr** [comment]
You could use csv2json and then transpose the result. Its fine it this isn't maximally efficient. It just has to work correctly until we can move to using HDF5.

**Comment by bilalshaikh42** [comment]
Looking at the library and the spec, it does not seem that headings can be placed as the first column, but they must be the first row. 

> 3. There maybe an optional header line appearing as the first line
       of the file with the same format as normal record lines.  This
       header will contain names corresponding to the fields in the file
       and should contain the same number of fields as the records in
       the rest of the file (the presence or absence of the header line
       should be indicated via the optional "header" parameter of this
       MIME type).  For example:

       field_name,field_name,field_name CRLF
       aaa,bbb,ccc CRLF
       zzz,yyy,xxx CRLF


https://tools.ietf.org/html/rfc4180

> You could use csv2json and then transpose the result. Its fine it this isn't maximally efficient. It just has to work correctly until we can move to using HDF5.

If I remember correctly, this did not work as csvtojson was unable to parse the file, since it strongly adheres to the spec. Looking at the package now though, I think I can just ignore the heading and treat the first element of each row as the heading manually.

**Comment by jonrkarr** [comment]
Excel and many other programs don't have this constraint. Surely another NPM package can parse this.
