### ISSUE TITLE
IMPORTANT: Get simulators is failing

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2681]
https://api.biosimulators.org/simulators/latest generates a 500 error

.dev does not. One difference is the content of the databases.

```
{"error":[{"status":"500","title":"Internal Server Error","meta":{"time":1625834833348,"url":"/simulators/latest"}}]}
```

**Comment by jonrkarr** [comment]
I deleted one version of OpenCOR in the database, and it now works. I suspect the issue is related to the large size of the returned information.

- [ ] I think we should try #2668
- [ ] If there's a memory limit that's being hit, can we provide more informative error message?

**Comment by bilalshaikh42** [comment]
The issue is the version of openCOR. The version is  '2021-05-19' which is
causing the error: Invalid argument not valid semver ('2021-05-19'
received). This was the reason we had previously been using a simple
comparison for the latest versions. I can add a case to check for a non
semver and use simple comparison in that case.

**Comment by bilalshaikh42** [comment]
I am a bit confused by the OpenCOR versioning. I see that OpenCOR has the latest release of v0.6, but their docker image is based on using dates for versions. Would it make sense to switch to the semantic version? 
If open is the only one in the database that is currently using this scheme, perhaps we can open an issue in their repo to see if switching to semantic versioning is possible? Alternatively, simply switching the "-" to a "." would be sufficient to get the simulators-api working
