### ISSUE TITLE
Clarification of datamodel for metadata

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2727]
We currently have the following data model for a described Identifier, which has a label and uri. 

``` typescript
label: string
uri: string
```
However, we are using the Uri field to provide a link out from the user interface. Should this be set as a URL instead? This would enable us to use the ```isURL``` validator built into the framework

**Comment by bilalshaikh42** [comment]
For example, the following is acceptable as a Uri, but we would need to recognize that it is taxon and maintain a mapping. 
```
label: Homo Sapiens
uri: NCBI:txid9606
```

Instead, we could require that the property be a URL like follows: 

```
label: Homo Sapiens
uri:  https://identifiers.org/taxonomy/9606
```

**Comment by jonrkarr** [comment]
Good point. I overlooked this important detail.

RDF uses URIs. URIs just need to be unique. They don't necessarily have to be resolvable as URLs. Furthermore, its ok for a URI to look like a URL, but not actually point to a resolvable address. As a result, we can't use a regular expression pattern to detect which URIs are URLs; we'd have to make HTTP requests to the URI to determine whether its resolvable. This is something we could validate, but we'd have to submit jobs to do this validation since it could take some time.

As a result, in the general case, we can't equate URIs and URLs.

One partial solution is to recognize some specific patterns of URI as URLs such as below. I don't love this because it would be limited to specific patterns that we enumerate.
- Things that begin with `https://github.com`, `https://identifiers.org`, etc.

One alternative is to recommend that OMEX metadata files explicitly define a URL for each URI (and then parse this information out). This could be similar to how we're recommending users put human-readable labels into metadata files because we don't know how to resolve this information in the general case. This would also provide flexibility to users to point to useful information about a URI rather than to the official definition of the URI. For example, a KiSAO term could be directed to an OLS page for the term, rather than http://www.biomodels.net/kisao/KISAO#KISAO_0000064, which redirects to the less helpful https://raw.githubusercontent.com/SED-ML/KiSAO/deploy/kisao.owl#KISAO_0000064.

Thoughts on this?

For now, I think we can equate URIs with URLs, getting the platform working, and then come back and refine this.

**Comment by bilalshaikh42** [comment]
I agree with the recommendation of always providing resolvable URLs in the metadata file. Perhaps we can go a little bit further with our recommendation and specify that the URL be from identifiers.org? Then we can treat anything that starts with identifiers.org as a URL, or otherwise as a URI.  

https://identifiers.org/biomodels.kisao:KISAO_0000064 for example points to the more useful bioportal page. Are there currently any identifiers that we are using for the "curated" list of metadata fields that do not have identifier.org ids?

For the "custom" metadata fields, we can include both a URL and URI field. I feel that a centralized mapping for the whole file would be harder to maintain that adding them to each term individually

**Comment by jonrkarr** [comment]
> Perhaps we can go a little bit further with our recommendation and specify that the URL be from identifiers.org? 

Yes, I've already tried to steer URIs to identifiers.org where possible. This has the additional advantage of being able to use identifiers.org to validate ids (against regular expression patterns registered with identifiers.org). BioSimulators-utils is already doing this. I meant to put a recommendation for identifiers.org in the documentation (https://biosimulators.org/conventions/metadata).

Unfortunately, not everything we want to use is registered with identifiers.org. One option is to ask our EBI collaborators to register additional namespaces which we don't own.

- [ ] GitHub: links to repos
- [ ] Linguist: programming languages
- [ ] SIO
- [ ] FunderRegistry
- [ ] Physiome model repository
- [ ] SED-ML URNs

**Comment by jonrkarr** [comment]
I separated creating additional identifiers.org prefixes to #2766

**Comment by bilalshaikh42** [comment]
One possibility for github repos is to have a DOI assigned. For example we have https://identifiers.org/doi:10.5281/zenodo.5057108
for this repo

**Comment by jonrkarr** [comment]
I got identifiers.org prefixes approved for all of the above.

Here's a GitHub example: https://identifiers.org/github/biosimulations/biosimulations

I think identifiers.org is simpler because it doesn't require the submitter to register their repo with zenodo. Of course, Zenodo can still be used to save a snapshot of something.

**Comment by bilalshaikh42** [comment]
Oh that's great. I did not realize that you could register a prefix  for an organization that you don't own. Using the GitHub prefix directly is definitely much better and simpler.

**Comment by jonrkarr** [comment]
I wasn't sure either. They approved it. They have a webform. Its easy to request more if needed.

Identifiers.org mainly keeps track of the owner of the namespace (e.g., GitHub Inc), rather than the person who submitted the namespace request.

**Comment by bilalshaikh42** [comment]
We are recommending identifiers.org as the uri. If the uri is a valid identifiers.org URL, then we can link out. If not, we can just display the uri
