### ISSUE TITLE
Handle `NaN`, `Infinity` in simulation results in API and apps

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2741]
See: https://github.com/biosimulations/Biosimulations/issues/2737

**Comment by jonrkarr** [comment]
Does the HSDS return infinity?

**Comment by bilalshaikh42** [comment]
I don't think this issue has shown up again

**Comment by jonrkarr** [comment]
Was the issue `NaN` or `Infinity`?

I fixed the `NaN` issue with tellurium by raising exceptions when tellurium returns `NaN`. I think most simulation tools raise errors on failures rather than returning `NaN` as tellurium does.

**Comment by jonrkarr** [comment]
I think we should label this as future (alternatively, this can be thought of as known current limitation) because simulation tools might want to return `Infinity` or `NaN`.

**Comment by jonrkarr** [comment]
As discussed today, VCell also uses `NaN` to report partially successfully simulations (individual tasks which partially succeeded). From HDFGroup/hsds#87, it sounds like the HSDS returns a superset of JSON similar to [JSON5](https://json5.org/). It doesn't sound like we want to use the `ignore_nan` HSDS option because it sounds like this also converts +/- Inf to null, which would lose information.

When an HDF5 data set has NaN or Inf, the HSDS responses likely look like this:
```json
{
  "values": [1, NaN, Inf, -Inf]
}
```

Because this is not valid JSON, this needs to handled when the response is parsed inside the HSDS client library. This can't be post-processed outside the library. There are NPM libraries which can parse this, including [json5](https://www.npmjs.com/package/json5).

**Comment by jonrkarr** [comment]
The HSDS appears to return data in a format compatible with [JSON5](https://www.npmjs.com/package/json5). When Axios receives output from the HSDS which contains NaN or Inf (JSON5), the `data` attribute of Axios' response is an instance of `string` rather than an instance of `object`. This string can then be parsed to an object by `JSON5.parse`.

I incorporated `JSON5.parse` into `libs/hsds/client/src/lib/dataset.service.ts`. This seems to work with the example in #2737 and the example below.

## Code to test HSDS
I've saved this code here in case we need to generate examples again to further explore the HSDS.

### Create dataset with NaN and Inf
```python
from biosimulators_utils.sedml.data_model import Report, DataSet
from biosimulators_utils.report.data_model import DataSetResults
from biosimulators_utils.report.io import ReportWriter, ReportReader
import base64
import numpy
import requests

report = Report(
    id='report',
    data_sets=[
        DataSet(
            id='d1',
            label='D1',  
        ),
        DataSet(
            id='d2',
            label='D2',
        ),
        DataSet(
            id='d3',
            label='D3',
        ),
    ],
)
results = DataSetResults({
    'd1': numpy.array([1., 2., 3.]),
    'd2': numpy.array([4., numpy.NaN, 6.]),
    'd3': numpy.array([7., numpy.inf, 9.]),
})
base_path = '.'
rel_path = 'sim.sedml'
ReportWriter().run(report, results, base_path, rel_path)
```

### Load HDF5 into HSDS
```bash
runId=61c22ea9b44ecd73d2c9736c
hsload \
    --endpoint https://data.biosimulations.dev  \
    --username ****** \
    --password ****** \
    --verbose \
    reports.h5 \
    /results/${runId}
```

### Get HDF5 from HSDS
```bash
hsget --endpoint https://data.biosimulations.dev  \
    --username ****** \
    --password ****** \
    --verbose \
    /results/${runId} \
    2/reports.h5
```

### Read data from HDF5
```python
base_path_2 = '2'
results_2 = ReportReader().run(report, base_path_2, rel_path)
```

### Get list of datasets
```python
response = requests.get('https://data.biosimulations.dev/datasets', 
    params={
        'domain': run_id + '.results',
    },
    headers={
        'Authorization': auth_string,
        'Accept': 'application/json',
    },
)
response.raise_for_status()
data_set_ids = response.json()['datasets']
print(data_set_ids)
```

### Read data directly from HSDS
```python
username = '******'
password = '******'
auth_string = username + ':' + password
auth_string = auth_string.encode('utf-8')
auth_string = base64.b64encode(auth_string)
auth_string = b"Basic " + auth_string

run_id = '61c22ea9b44ecd73d2c9736c'
data_set_id = 'd-e9e8ad56-ef34fa21-bce7-b90872-0ae8d2'

response = requests.get('https://data.biosimulations.dev/datasets/' + data_set_id + '/value', 
    params={
        'domain': run_id + '.results',
    },
    headers={
        'Authorization': auth_string,
        'Accept': 'application/json',
    },
)
response.raise_for_status()
response.json()
```
