### ISSUE TITLE
Distinguish response types for each combine service endpoint

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3091]
I might be reading this incorrectly, but it seems that the manifest endpoint and sedml  specs endpoint are both returning the same content 

https://combine.api.biosimulations.org/ui/#/COMBINE/src.handlers.combine.get_sedml_specs_for_combine_archive.handler

**Comment by bilalshaikh42** [comment]
I see my misunderstanding. The return type 'combinearchive' but internally has different content. This was not clear on the generated code, but should work fine

**Comment by jonrkarr** [comment]
That's correct. The two endpoints use the data structures, but use them slightly differently.

In one case, the children are instances of `SedDocument`. In the other case, the children are instances of `CombineArchiveContentFile`. `CombineArchiveLocationValue` illustrates how this works.

In the TypeScript code, I've differentiated between these two cases. In the TypesScript code I have a separate type for `SedCombineArchiveContent`, which I'm using to  mean all of the content of a COMBINE archive of file type SED-ML. 

Because ApiCurio is a bit more cumbersome, I reused classes there.

**Comment by bilalshaikh42** [comment]
One issue is that this prevents the library (generated typescript) from being able to strongly type the responses for each different endpoint. So the code ends up needing to be aware of the return type for each endpoint rather than just get the information from the endpoint. I am not sure if there is a good way to address this other than having different return types for each endpoint in the open API spec.

**Comment by jonrkarr** [comment]
This could easily be handled at the typescript client level. Also, the project service you created is doing the save thing except the types are `any`.

**Comment by bilalshaikh42** [comment]
The issue is with the gnerated typescript code. Since the library that interfaces with the API is using the spec, it types all the responses as the same object. It also seems that there are places where the typescript models are not equivalent to what the library has and the types cannot be interchanged. 
 The project service I absolutely agree needs to have the typing added, just hadn't included it yet since we are switching to storing the info in the database/api

**Comment by jonrkarr** [comment]
This is fairly easy to fix by editing the YAML and then uploaded that to APICurio.

**Comment by bilalshaikh42** [comment]
Perfect. This might also allow us to just use the libraries datamodel as the shared datamodel instead of maintaining a separate typescript version
