### ISSUE TITLE
Change 'Master' field on Files to 'Main'

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3147]
Should we rename the field on our end? I know this is a carryover from the sedml but it should be easy to maintain as all of our code only interacts with the API now and not the combine-service directly

**Comment by jonrkarr** [comment]
I thought about this too. I used "main" in the UI, but kept "master" in code. I'm fine with switching this. We already have subtle divergences from the SED-ML terminology -- to be more consistent than SED-ML is.

**Comment by jonrkarr** [comment]
I submitted an issue about replacing this concept in the COMBINE archive format earlier this year -- sbmlteam/libCombine#35. @matthiaskoenig is also pushing to replace the "master" concept. When the COMBINE archive format changes, we'll align with that. Until then, we could rename to "main" in the data models. The UI already displays "main" rather than "master".

**Comment by jonrkarr** [comment]
Let's address this when the COMBINE archive format addresses this (assuming this is relatively soon).
