### ISSUE TITLE
Change SimulationRun object to take in a BiosimulatorsId instead of a simulator/version pair

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3164]
@jonrkarr  this would allow the database the store the biosimulators id directly so that there is no need to do mapping. This way those who are using the API to pull the simulation run would actually receive an id to an existing simulator object.

 There would not be much change required to the UI,  just mapping the current fields to the new term
The only tricky part would be mapping these ids to the correct images on the HPC, but this should be possible. I just went with the method akhil had when he set it up, but it should be easy enough to work out.

Thoughts?

**Comment by jonrkarr** [comment]
What is a `BiosimulatorsId`? Object with two fields `id` and `version`?

**Comment by bilalshaikh42** [comment]
Sorry, that was clear. basically just simulator/version as one string. I
know it can be easily reconstructed, but it just seems to make more sense
in the backend to have one id for each simulator

**Comment by bilalshaikh42** [comment]
But now I am unclear on one thing. What was the mapping that you mentioned
needing to do because of the way that the simulator name and version were
stored? That was the initial issue that made me think about this, but now I
don't remember if there was any sort of problem

**Comment by jonrkarr** [comment]
This is the information I'm trying to display in the dispatch and platform apps (more specifically in a component in the dispatch app and a component in `shared/project-ui`)
- Name of simulator
- Version of simulator

Presently, I'm getting the simulator `id` and `version` from the `SimulationRun` and then using the simulators API to get the `name` of the simulator from its `id`.

This could be factored differently.

**Comment by jonrkarr** [comment]
A combined id field would be fine internally. I'd like to keep separate fields with the individual id and version attributes as well because we don't necessarily want to display the two together in the UI, and it would be annoying to have to parse that out. Also, I think contributors should submit the two pieces of information separately because they should be focused on registering ids for simulation tools.

The revised data model could look like this:
- `id`: read/write; no change
- `version`: read/write; no change
- `digest`: read/write; no change
- `idVersion`: read only, new attribute (e.g., `${id}:${version}`).

For simulation runs, a combined id/version attribute could be added and all of the simulator properties could be grouped together
- `simulator`:
  - `idVersion`
  - `id`
  - `version`
  - `digest`

**Comment by bilalshaikh42** [comment]
From the users point of view, the simulators and versions make more sense as being separate.
