### ISSUE TITLE
Client always calls dev COMBINE API

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3180]
i don't remember setting the configuration of the combine service to be dependent on the environment, so it must be always calling the dev deployment, even in production

**Comment by jonrkarr** [comment]
The deployed dispatch app always calls `org`.

`https://combine.api.biosimulations.dev` is hardcoded into `libs/combine/api-client/src/lib/api/simulationProjectsCOMBINEOMEXArchives.service.ts`. I guess this happens because this is the first URL in the OpenAPI spec.

The `configurationFactory` needs to be linked to `Endpoints` or the `generate-combine-client` script can modify how configuration is passed in.

**Comment by bilalshaikh42** [comment]
The associated commit may not work since config service is provided async.  This will always cause the env to be null, leading to the dev basepath selected by default.

**Comment by bilalshaikh42** [comment]
I am working on this in #3495

**Comment by bilalshaikh42** [comment]
I am working on this in #3495

**Comment by jonrkarr** [comment]
I saw that. In practice, it seemed to work fine. The client library has to be changed to accommodate that.
