### ISSUE TITLE
GET project is failing

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3304]
Example:
-  https://api.biosimulations.dev/projects/NFAT-translocation-Tomida-EMBO-J-2003
-  https://api.biosimulations.org/projects/NFAT-translocation-Tomida-EMBO-J-2003

Log excerpt
```
[31m[Nest] 1  - [39m10/18/2021, 2:39:14 AM [31m  ERROR[39m [38;5;3m[DefaultFilter] [39m[31mTypeError: Cannot read property 'length' of undefined[39m
TypeError: Cannot read property 'length' of undefined
    at /app/main.js:1987:12
    at /app/node_modules/@nestjs/core/helpers/context-utils.js:36:28
    at resolveParamValue (/app/node_modules/@nestjs/core/router/router-execution-context.js:145:31)
    at Array.map (<anonymous>)
    at pipesFn (/app/node_modules/@nestjs/core/router/router-execution-context.js:150:45)
    at /app/node_modules/@nestjs/core/router/router-execution-context.js:37:36
    at InterceptorsConsumer.transformDeferred (/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:28)
    at /app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:15:48
    at Observable._subscribe (/app/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:36)
    at Observable._trySubscribe (/app/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
[32m[Nest] 1  - [39m10/18/2021, 2:39:14 AM [32m    LOG[39m [38;5;3m[DefaultFilter] [39m[32mObject:[39m
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "meta": {
        "time": 1634524754092,
        "url": "/projects/NFAT-translocation-Tomida-EMBO-J-2003"
      }
    }
  ]
}
```

**Comment by bilalshaikh42** [comment]
This is caused by the changes in 11cc90f601129dd14fbac3e27c4808fa5b14af87

The parameter names were changed without changing the parsing of the param names Running the API and going to the documentation shows that there are now two separate params being parsed. 

Changes to the API really require running the API and trying out the endpoints since we do not have sufficient tests

**Comment by bilalshaikh42** [comment]
Many of the documentation additions were already present, through other helper decorators that are designed to prevent having to repeat the same information across endpoints. 
For example, the "permissions" decorator has already built in the Unauthorized and Unauthenticated decorators, which is why they appear on the Swagger UI automatically when a route requires permissions

**Comment by bilalshaikh42** [comment]
Running the API and verifying the endpoints on the UI is essential whenever a change to the API code is made, as it is usually sufficient to catch these.  Obviously, that is not a good enough reason to not have sufficient tests, but it is able to catch the majority of the issues that  we have had with API breaking only being noticed after deployment
