### ISSUE TITLE
PUT `simulator/{id}/{version}` is broken (by NestJS or Mongoose updated?)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3305]
Example: https://api.biosimulators.org/simulators/ginsim/3.0.0b

Sample error:
```
{
  "error": [
    {
      "status": "500",
      "title": "Database StrictModeError",
      "detail": "Path `created` is immutable and strict mode is set to throw.",
      "source": {
        "pointer": "/biosimulators"
      }
    }
  ]
}
```

**Comment by bilalshaikh42** [comment]
might have the same cause as #3304 
The message seems to suggest that updating the simulator is causing the "created" date to also change, though it has been explicitly set not to be changeable. The error is actually revealing what must have previously been a repeat of #2570

**Comment by bilalshaikh42** [comment]
Confirmed that's it's the same issue, but the validation is working better now. 

https://github.com/biosimulations/biosimulations/blob/d05fabdc24efbe86fb12710e6dcbb293cb16318b/apps/simulators-api/src/simulators/simulators.service.ts#L105

Instead of overwriting the document here, the fields should be replaced individually, and then document saved.
