### ISSUE TITLE
Simplify special handling of payload too large errors once properly handed by NestJS

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3349]
Once NestJS provides better error handling (see nestjs/nest#5990), our `HttpExceptionFilter` can be removed.

**Comment by bilalshaikh42** [comment]
I am not to sure what this adds beyond the current implementation. The filter that  I have is designed to return JSON-API Error Documents, but that could be changed to anything. Where the format really adds value is when it specifies the path containing errors for things such as schema validation.

If there are more details/other messages that you want to return to the user, instead of throwing an HTTP exception, you can throw a BioSimulationsException which provides far more options for customization

---
To clarify, the "this" referred to the nestjs changes. I now see that it would be reported correctly as a HTTP exception rather than an unknown error

**Comment by bilalshaikh42** [comment]
98fb49d651c01d621d175051cb030621b273034a seems to introduce a completely new library for an error handler instead of including it in the already existing error handlers. we have a module for nest that when imported provides filters and handlers for various types of errors, not just this one type. What was the use case that motivated this change? It would be much better to include that case as one of the options already handled by the existing library

**Comment by bilalshaikh42** [comment]
This also breaks the response of the health endpoints, since the global filter is now catching those errors instead of skipping them as was set in the HTTP exception filter that is defined in ```libs/shared/exceptions/filters```
Additionally, this will catch ALL errors, meaning that none of the special handling for various different cases that is found in the various filters will now apply. I am going to remove the filter for now, and then the specialized handling for this case can be added into the ```libs/shared/exceptions/filters``` library

**Comment by jonrkarr** [comment]
Prior to 98fb49d651c01d621d175051cb030621b273034a, there were 500 errors with no information.

It has to catch all error due to limitations of NestJS.

The health endpoints could be handled appropriately in the new error filter.

**Comment by jonrkarr** [comment]
This a note that special handling in `libs/shared/exceptions/filters/src/lib/default.filter.ts` for 413 errors could be removed once the underlying issue is better handled by NestJS.

https://github.com/biosimulations/biosimulations/blob/e70ae45c79304208c108bea298cabe634d64fc54/libs/shared/exceptions/filters/src/lib/default.filter.ts#L32

**Comment by bilalshaikh42** [comment]
It seems that the issue linked was merged and released a while ago, which makes me think there might still be some issue or the handling that we have with the rest of the errors may be causing the issue

**Comment by jonrkarr** [comment]
From the comments, it wasn't clear to me that the issue was really addressed.
