### ISSUE TITLE
Use https://www.ag-grid.com/features-overview/

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#34]
to display simulation data, available simulations, search results etc. 
Perhaps have it as its own components, feed in search data etc

**Comment by bilalshaikh42** [comment]
@gmarupilla  I had made this note for the visualization results, but I see that you have made something simmilar for the simulations. Do you think it would be good to have this be a main component as use it for all the tables on the site?

**Comment by gmarupilla** [comment]
I do not know what this issue is about exactly. As far as I know, the code I've written till now, you upload a `sbatch file`, select available `omex` and `solver` on HPC cluster (currently dummy files), and run the simulation which means running the selected `SBatch file` on HPC cluster. Currently, the selection of `omex` and `solver` is not even being used anywhere on the execution command, but is being saved to database.

So, in context to the information I have, can you tell me what's the problem statement again?

**Comment by gmarupilla** [comment]
But, In today's meeting Ion suggested to use real omex archive file, which gives SBML file (`.xml` format) and Copasi model (`.cps` format) with specific time point.

**Comment by bilalshaikh42** [comment]
Sorry, I mean in regards to any future components that we may use for showing past simulations or data from simulations. I was going to use this anyway for the past visualizations browsing but if you will be making similar tables for displaying past simulations it may save us some work to make one component (app-table) and then use it for our respective needs. The upload portion wouldn't be related to this

**Comment by bilalshaikh42** [comment]
https://www.ag-grid.com/angular-getting-started/
Guide for using angular-grid

**Comment by bilalshaikh42** [comment]
included in the data-table component
