### ISSUE TITLE
[Bug]: Dispatch service does not produce logs that can be properly validated by the api

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3482]
### Location

BioSimulations API

### What happened?

When running a simulation with an invalid omex archive, the job fails as expected. However, the dispatch service's upload of the log also fails due to the following validation error

```
               "type": "ValueError"
              },
              "property": "exception",
              "children": [
                {
                  "target": {
                    "message": "`/root/input.omex` is not a file.",
                    "type": "ValueError"
                  },
                  "property": "category",
                  "children": [],
                  "constraints": {
                    "isString": "category must be a string",
                    "isNotEmpty": "category should not be empty"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

### What made it happen?

Running a simulation that fails

### Version

Development (Deployed on a .dev domain)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
This seems to be casued by the simulators, as they are not outputting a category for the exception.

**Comment by bilalshaikh42** [comment]
Seems that the simulators are outputting "type" instead of "category" for the exceptions. I added a temporary workaround for this in #3484

**Comment by jonrkarr** [comment]
Thanks for catching this. Simulators are intended to use the `type` attribute. I made a mistake when encoding the data model into Typescript. The COMBINE API also showed `category` rather than `type`; this because the COMBINE API is importing models from the API, creating a copy of the same models withing the YAML specifications for the COMBINE API (in ApiCurio this is stored as reference; I'm storing a de-referenced version of this in this repository to avoid needing to resolve that dynamically).
