### ISSUE TITLE
Simplify Auth0 scopes

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3575]
- [x] Replace scopes in this repo
  - [x] `delete:Files` --> `delete:SimulationRuns`
  - [x] `delete:Logs` --> `delete:SimulationRuns`
  - [x] `delete:Metadata` --> `delete:SimulationRuns`
  - [x] `delete:Results` --> `delete:SimulationRuns`
  - [x] `delete:Specifications` --> `delete:SimulationRuns`
  - [x] `read:Files` --> `read:SimulationRuns`
  - [x] `read:Logs` --> `read:SimulationRuns`
  - [x] `read:Metadata` --> `read:SimulationRuns`
  - [x] `read:Results` --> `read:SimulationRuns`
  - [x] `read:Specifications` --> `read:SimulationRuns`
  - [x] `write:Files` --> `write:SimulationRuns`
  - [x] `write:Logs` --> `write:SimulationRuns`
  - [x] `write:Metadata` --> `write:SimulationRuns`
  - [x] `write:Results` --> `write:SimulationRuns`
  - [x] `write:Specifications` --> `write:SimulationRuns`
- [ ] Delete scopes in Auth0
  - [ ] `delete:Files`
  - [ ] `delete:Logs`
  - [ ] `delete:Metadata`
  - [ ] `delete:Results`
  - [ ] `delete:Specifications`
  - [ ] `read:Files`
  - [ ] `read:Logs`
  - [ ] `read:Metadata`
  - [ ] `read:Results`
  - [ ] `read:Specifications`
  - [ ] `write:Files`
  - [ ] `write:Logs`
  - [ ] `write:Metadata`
  - [ ] `write:Results`
  - [ ] `write:Specifications`

**Comment by bilalshaikh42** [comment]
Here is a blog post that explains the issue with auth much better than I can. Currently, we are using the scopes as explicit permissions, which fundamentally is different from delegation. As the article warns, we can use scopes to implement the first case, but that breaks the second case. 
https://auth0.com/blog/on-the-nature-of-oauth2-scopes/

The way to address this is to not use scopes at all, but designate certain roles for the various operations. Scopes can then be used by the individual users/repositories in the intended way as delegation not permissions. 

I can make the changes to use this approach after we import models from the repositories since we do not need it until then.

**Comment by bilalshaikh42** [comment]
Alternatively, I can work on that this week, and make the needed changes by end of day tomorrow, and then work on importing models starting monday

**Comment by jonrkarr** [comment]
This issue and #3575 aren't intended to be a complete solution, just a quick fix to one issue which can be done without more significant refactoring.

If you think you can complete this this week, go ahead. Please also finish up #3534 so the COMBINE API is being tested again. I'd also like to wrap up the user guide (#3577).

I'm trying to be careful about time management because models and simulations are likely to take significant effort. The model repositories are messy resources with little documentation. While I've worked through at least one example with each one, its hard to know how many other problems we're going to encounter. BiGG was relatively easy, although no one is really responsible for BiGG to correct the issues I found. On the other hand, BioModels has taken a lot of work. Its hard to know where ModelDB, PMR, etc. will fall in this spectrum.

**Comment by bilalshaikh42** [comment]
Done via auth0
