### ISSUE TITLE
Clean up building apps

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3627]
`.github/workflows/cd.yml`
```
mv libs/shared/environments/src/lib/environment.stage.ts libs/shared/environments/src/lib/environment.prod.ts && nx build ${{matrix.app}} --prod --with-deps
```

The above fragment is confusing and forces deployment logic into the code
- The `stage` environment is used rather than `dev`
- The build target is `production` rather than `development`
- Moving files is used rather than the more canonical `--configuration development` option and file replacements
- Not handling the environment at building forces logic for handling environment into the endpoints class and into code which calls the endpoints class. A clearer strategy for managing local development would avoid this, and enable separate configurations for different apps. This would be convenient for local development with some resources running on the `dev` deployment.

**Comment by bilalshaikh42** [comment]
``` The stage environment is used rather than dev```

This was done to prevent changes to the dev environment making there way into deployments. We can change this sure

``` The build target is production rather than development```

The build target is being used to modify the settings of the build process itself. That is how much optimization, bundling, code splitting to use and features such as enabling of the service worker. 

These settings are going to be the  "production" version for all deployments other than local testing. Setting the dev target to include these will dramatically slow down the building and serving locally

File replacements are only really a small part of the various build targets

``` Moving files is used rather than the more canonical --configuration development option and file replacements```

This is  because the configuration of the app needs to copy over both build settings, like mentioned above, as well as file replacements. So if we want to create a new deployment, we simply add a file in the form of environment.ENV.env, where ENV can represent any name. Then the builds have 2 steps:
1. Replace the file environment.PROD.env with the target
2. Run the production build 

Defining these in the apps would require keeping them in sync across various apps, and changes to the main project configuration even when just a small line needs to be changed. This makes auto deployment of branches and scripts to modify deployment much more difficult to use

```Not handling the environment at building forces logic for handling environment into the endpoints class and into code which calls the endpoints class. A clearer strategy for managing local development would avoid this, and enable separate configurations for different apps. This would be convenient for local development with some resources running on the dev deployment.```

I agree that the Endpoints class has gotten confusing. Its use has deviated from its original purpose. 

We can create a set of endpoints that are defined at compile-time specifically for the front-end apps. These can then be passed into the environments class using the configuration option as you suggest.

The backend needs to be able to read env variables for URLs. Otherwise, we need to manage docker tags for various environments, which inherently limits the options we have. We then need to keep track of these tags and make sure the right one is deployed to each environment etc. This also does not allow testing a docker image in one environment and then promoting it to another. For example, load tag v1 to dev, then move to prod when it has been tested. Now, prod would need a different image from what was tested.

The only deployment-specific logic that we needed was to account for localhost not being accessible from the HPC. This can be easily remedied by having 2 environment variables one for internal and one for external. The only "deployment" knowledge that the apps need is whether they plan to use the URL to make a call themselves, or to pass it to something else.
Otherwise, I don't see where else this deployment logic can come into the app. 

My proposal is to define the internal and external versions of each endpoint base in the current endpoint class as usual. Front-end apps would use the environment file to pick out of a set of choices since this is needed at build time.

Backend apps would automatically load the correct root URLs from environment variables
