### ISSUE TITLE
Dev API is down

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3647]
Cannot use Argo app to explore the reason because it is also down.

**Comment by bilalshaikh42** [comment]
The dev api is down due to recent changes that have added the account management service to the API. The proper secrets were not added to the deployment.

**Comment by bilalshaikh42** [comment]
There are a few problems with the latest changes. We do not have access to the auth0 organization features with our account. Organization and account information should really be managed in our database rather than auth0. The API especially should not be using the management client, as it does not have the permissions to do so. That was what the account API was for

**Comment by bilalshaikh42** [comment]
It might make sense to combine the functionality, into the one API, but we should first discuss the use-case and architecture a little bit.

**Comment by bilalshaikh42** [comment]
I have added the needed token to get the API running, but further debugging might be needed to determine if this approach works

**Comment by jonrkarr** [comment]
I saw the notice about not having organization features, but using organizations seems to work fine.

We need to move past building infrastructure.

**Comment by bilalshaikh42** [comment]
I worry about the feature being disabled at some point since it is new, but we can keep it as is if you prefer

**Comment by jonrkarr** [comment]
If that happens, we could manage organizations via Auth0 user and machine metadata, create a MongoDB collection for them, or explore an enterprise plan, which we appear to already have. I think our limited time is better spent on creating content.
