### ISSUE TITLE
Simplify usage of  ```create-simulation-project``` and ```dispatch-component```

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3720]
There are two components that seem to be forms for submitting a project, one for running a simulation and the other for submitting a project. Both take in many of the same form inputs and have different validators attached in the same file. this is difficult to parse and changes to one are not reflected in the other. 
The forms ideally would be combined as one form that has varying levels of validation depending on weather the project is to be published or not

**Comment by jonrkarr** [comment]
These forms have distinct functions and different inputs and outputs and thus distinct validation. Currently, there's a button to pass the output of the first to the input to the second.

We need to focus on creating modeling projects that are already available rather than UIs that comparatively few people will use to create COMBINE archives.

**Comment by bilalshaikh42** [comment]
I see I misinterpreted the purpose of the form based on the name since we have overloaded the term project. I assumed "project' meant published project. Now I see that the functionality for submitting a project and submitting simulation run use the same underlying form, with added validation when submitting. This can be disregarded.
