### ISSUE TITLE
Results endpoint should return partial data when possible

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3725]
For example: https://run.biosimulations.dev/simulations/61a5440b4a8b188bb74c1a51#tab=log
The run failed. so it is likey that some or all data was not output. 

Trying to get the results (without data) works fine:
https://api.biosimulations.dev/results/61a5440b4a8b188bb74c1a51?includeData=false

However, trying to get the data with results causes a 500 error: 
https://api.biosimulations.dev/results/61a5440b4a8b188bb74c1a51?includeData=true

This is by design since the dimensions of that data were probably inconsistent and so the processing throws an error. However, it would be more user friendly to
1. display a more informative message
2. return the data that is available even if it incomplete

@jonrkarr I am not sure how we want to handle point 2. Should this be limited to only tasks that have completed or all data?

**Comment by jonrkarr** [comment]
Multiple things have to be done to properly deal with errors.

This sounds related to the NaN issue with the HSDS. The underlying issue is that we're not properly retrieving NaN and +/-Inf from the HSDS. Currently, the HSDS truncates the data (presumably at the first NaN or Inf). This makes it hard to understand what the data was intended to be. Reshaping the response from the HSDS doesn't fix the problem because data has already been lost, as well as its original shape. I've added a step to raise an error when this truncation happens because when it happens the API doesn't receive enough information to properly interpret the data.

I think the solution is to properly deal with NaN and Inf. At the very least, they need to be converted to null (which would confuse NaN and Inf). Once handled, the error mentioned above would never been raised.

In addition, we need to see what Plotly and Vega do with NaN/null values, and if necessary truncate the data sent to them.

**Comment by jonrkarr** [comment]
This sounds redundant with #2741.
