### ISSUE TITLE
Permissions to delete simulation tools is broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3767]
This is error I now see when trying to use https://api.biosimulators.dev/simulators. There is no Auth0 "Admin" role.

This is a relatively new error. This wasn't present a few weeks ago.

```json
{
  "error": [
    {
      "status": "403",
      "title": "You do not have the Admin Role",
      "detail": "\"You do not have the Admin Role\""
    }
  ]
}
```

**Comment by bilalshaikh42** [comment]
This is a holdover from when we were using roles more directly instead of fine-grained permissions. The latest changes to Auth0 removed the code snippet that was adding the "Admin" role to our accounts.  This should be fixed by #3769. An additional permission is added to allow for the deletion of all simulators.
