### ISSUE TITLE
Replace cookies with local storage

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3790]
- [ ] Replace cookies https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies
- [ ] Edit Privacy policy: Change documentation to say we use "performance cookies"
     https://docs.biosimulations.org/about/privacy/#how-we-collect-personal-data

**Comment by bilalshaikh42** [comment]
https://github.com/h5bp/html5-boilerplate/issues/1444#issuecomment-213000510

**Comment by bilalshaikh42** [comment]
@jonrkarr this is effectively done. It was not as simple as I thought since the new version of google analytics does not support the configuration as above. I was able to use google tag manager to set up the config, but we effectively lose all information other than page views. 

Looking at the following two pages, I think we can actually leave the cookies in. The cookies are used to keep track of sessions, not track users. I think this falls under performance cookies, and should not be a problem Perhaps we can clarify this in the policy/ submissions. 

https://www.cookiepro.com/knowledge/tracking-cookie/
https://www.cookiepro.com/knowledge/what-are-performance-cookies/

**Comment by jonrkarr** [comment]
Using cookies and describing them "performance cookies" seems fine to me. Nucleic Acids specifically says "tracking cookie". In that case, please revise the statement in the privacy policy (`docs/about/privacy.md`).
