### ISSUE TITLE
Increase size limit for logs of simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3828]
The log for runs of [this archive](https://github.com/biosimulations/biosimulations/files/7729339/iCHOv1_DG44.zip) can no longer be uploaded
```
[31m[Nest] 1  - [39m12/16/2021, 5:06:04 PM [31m  ERROR[39m [38;5;3m[LogService] [39m[31mThe log for simulation run '61bb6cbd48f42dceb5bc56ef' could not be created: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit[39m
```

**Comment by jonrkarr** [comment]
The log still cannot be uploaded. Example: https://run.biosimulations.org/simulations/61bbabc6297bc08e2f83de43.
`nfs/biosimulations/prod/simulations/61bbabc6297bc08e2f83de43/log.yml`

YAML version of log is 12MB. This may be breaking the MongoDB limit.

Ideally, we would provide a clear error message about this.

Also, I should make biosimulators-utils truncate such long logs and/or filter out warnings with COBRApy.

**Comment by bilalshaikh42** [comment]
@jonrkarr  could you take a look at the branch post-log-debug?
I made some changes just to debug this, and I am confused as to the cause: 
 
1. the construcctor for the log processor is set up   so that as soon as you start  the dispatch-service it will try to post the log. 
2. The API main file more explicitly sets the body size limit
3. The json for the log is written to file to debug.

With this, If I start the service and API I get the error that the body is too large. 

Then, I send the log via curl using the JSON file. It goes through just fine
 
To confirm that the limit is set correctly, I reduce the limit to below 11MB (the size of the log). Now, both the curl command and the service report the error, as expected 

However, I cannot get the service to post successfully, even if I increase the limit dramatically.

Any thoughts on what is going on? This is all reproducible locally, so can't be a deployment issue

**Comment by jonrkarr** [comment]
Seems like there's a limit on what the service can send, or maybe what it can serialize to JSON. I'm not familiar with sender-side limits, but I guess it's possible there could be configuration for this. I'd be spirited if it were a memory limit since you're running this on your machine. I'm more familiar with receiver-side limits.  

Did you try searching Google for such a client side limit?

Are you uploading the same JSON with curl? I ask because the dispatch service adds content to the log beyond what the simulation tools collect. This might be enough to push the content beyond Mongos document size limit. This would explain why changing the payload limit has no affect. 

Can you save the content that the dispatch service is trying to upload to a file, and then try to upload that directly to mongodb (e.g. through Atlas)?

**Comment by bilalshaikh42** [comment]
Of course, it's a client-side issue. The two error messages for the body being too large on the server and on the client are similar enough that I didn't even think to check. Should be resolved shortly.

Thanks!
