### ISSUE TITLE
Handle transient issues with access to s3 bucket

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3896]
The s3 bucket hosted at Uconn may be causing issues with HSDS and uploading files. We can switch some functionality over the a google cloud bucket temporarily to see if that resolves the issues/speeds up the file uploads.

See https://github.com/biosimulations/biosimulations/issues/3811#issuecomment-1000976505 for context/motivation

**Comment by jonrkarr** [comment]
With a few minor changes, I think we could use Google cloud as temporary storage until archives and their contents are successfully copied to the uconn bucket. I'm thinking we wouldn't add a job to the dispatch queue until transfered, and add a transfer queue between the submission and the dispatch queue.

**Comment by bilalshaikh42** [comment]
I am not sure what that would achieve. Is the point simply to return a response to the user before waiting for the transfer? In that case, we can simply wait to upload the archive after returning a response, so this would just be a part of the "dispatch" step. There is no need for a second bucket in that case

**Comment by jonrkarr** [comment]
To the user, submissions would reliably be accepted rather than rejected. To users, the systems would appear more reliable. Instead of requests being rejected, users would potentially experience slower runs when there's bucket connection issues. This just requires some form of temporary storage.

**Comment by jonrkarr** [comment]
With a change like this, it should become unnecessary for biosimulations-bigg to retry submissions because the retry logic (for uploading to the bucket would effectively be internalized into the dispatch service).

**Comment by bilalshaikh42** [comment]
> To the user, submissions would reliably be accepted rather than rejected. To users, the systems would appear more reliable. Instead of requests being rejected, users would potentially experience slower runs when there's bucket connection issues. This just requires some form of temporary storage.

Right. I think this can be achieved without the need for a separate bucket. We can simply upload the files to the bucket after returning a response to the user instead of before. Any issues can be handled with retries.

**Comment by jonrkarr** [comment]
I suggested a queue approach because retrying isn't intend for many retries, such as when the bucket is down for hours. If retrying eventually fails after a maximum number of retries is exhausted, the status of the simulation run and its log would need to be updated accordingly so that users can access information about the reason for the failure.

**Comment by jonrkarr** [comment]
Summary of changes I've made:
- Moved downloading and uploading of COMBINE archives from API to dispatch service
- Added retrying of S3 operations
- Increased S3 upload time out to 10 minutes

Todo
- [x] Deploy changes to prod 
- [x] Test, e.g., with BiGG models
- [ ] We could maybe reduce the number of replicas of the API and their memory, leaving more for the dispatch service

**Comment by jonrkarr** [comment]
Test observations
- Simulations could be submitted much more quickly than before (API response time was much less)
- This seems to have taxed our system much more, result in a new set of issues
- Roughly 50% of runs did not succeed
  - 16 failed to upload results to HSDS. Example: 61d8fc19e6309d9a41b1bd3a
  - 4 failed with mkdir in `submitJob`. Example: 61d8fc5e0eb55fbb5372d6b6
     - Somehow `submitJob` is getting run twice for some runs. Might be due to Redis failing and restarting. 
     - Changing `mkdir` to `mkdir -p` will just create problems further downstream.
  - 12 stuck in running state. Example: 61d8fc2d0eb55fbb5372d680
     Feels like the result of the Redis or the dispatch service failing and dropping the monitoring of a run
  - 9 stuck in created state. Example: 61d8fd6357bea0f4bef61ac2
    Maybe similar reason
  - 1 failed because metadata couldn't be uploaded (feels like the API was down and 502 errors weren't retried successfully)
  - 81 503 errors between API and dispatch-service
  - 24 502 errors between API and dispatch-service
  - 1 504 error between API and dispatch-service
- API pods went down multiple times
- Redis health was degraded (COMBINE archives are now being stored there for the dispatch queue)

Takeways
- The issue seem to be with the resources of the deployment, rather than the logic in the code
- I think more resources need to be allocated to HSDS, Redis, dispatch service, and API
- If the above isn't sufficient, we may need to be more careful about popping tasks off our queues and only popping them off once the task is complete rather than when the task starts to avoid losing track of tasks
- We could consider throttling the processing of the dispatch queue

@bilalshaikh42 thoughts?

Notes on job failures
```
HSDS
    iAF1260: FAILED
    iB21_1397: FAILED
    iEC1344_C: FAILED
    iECO103_1326: FAILED
    iECs_1301: FAILED
    iEK1008: FAILED
    iEcDH1_1363: FAILED
    iEcE24377_1341: FAILED
    iEcSMS35_1347: FAILED
    iG2583_1286: FAILED
    iJR904: FAILED
    iNRG857_1313: FAILED
    iSFxv_1172: FAILED
    iS_1188: FAILED
    iYO844: FAILED
    iYS854: FAILED
    ic_1306: FAILED

mkdir
    iEC1349_Crooks: FAILED
    iEC1364_W: FAILED
    iEC55989_1330: FAILED

iNF517: FAILED

RUNNING
    iAPECO1_1312: RUNNING
    iBWG_1329: RUNNING
    iE2348C_1286: RUNNING
    iEC1356_Bl21DE3: RUNNING
    iEC1368_DH5a: RUNNING
    iEC1372_W3110: RUNNING
    iECABU_c1320: RUNNING
    iECBD_1354: RUNNING
    iECDH1ME8569_1439: RUNNING
    iECD_1391: RUNNING
    iECIAI39_1322: RUNNING
    iECNA114_1301: RUNNING
    
CREATED
    iECO111_1330: CREATED
    iECO26_1355: CREATED
    iECOK1_1307: CREATED
    iECP_1309: CREATED
    iECS88_1305: CREATED
    iECSE_1348: CREATED
    iECSF_1327: CREATED
    iECSP_1301: CREATED
    iECUMN_1333: CREATED
```

**Comment by bilalshaikh42** [comment]
> * Simulations could be submitted much more quickly than before (API response time was much less)

There have not been any changes to the API other than increasing memory. ( I have not pushed the s3 changes yet). This might be from having more controllers for the ingress availalble

> * 16 failed to upload results to HSDS. Example: 61d8fc19e6309d9a41b1bd3a
Is this due to null/infinity like mentioned previously? Or just load? 




> 4 failed with mkdir in `submitJob`. Example: 61d8fc5e0eb55fbb5372d6b6
> * Somehow `submitJob` is getting run twice for some runs. Might be due to Redis failing and restarting.
> * Changing `mkdir` to `mkdir -p` will just create problems further downstream.

I am not sure what you are refering to here. I see the error message '`/root/project.omex` is not a valid COMBINE/OMEX archive' which makes me think that the issue is with downloading the archive or mounting the folder. Which directory creation failed? 



> * 12 stuck in running state. Example: 61d8fc2d0eb55fbb5372d680
>   Feels like the result of the Redis or the dispatch service failing and dropping the monitoring of a run
> * 9 stuck in created state. Example: 61d8fd6357bea0f4bef61ac2
>   Maybe similar reason

This has never happened previously. Redis is very reliable and should not be going down under the conditions that we have set. 



> * 81 503 errors between API and dispatch-service
> * 24 502 errors between API and dispatch-service
> * 1 504 error between API and dispatch-service

This seems expected if as you mention the pods are failing

**Comment by bilalshaikh42** [comment]
> * Redis health was degraded (COMBINE archives are now being stored there for the dispatch queue)

This is the cause of the issue. This is not a valid approach to this. Redis is not designed to hold binary data and is not at all suitable for this purpose.  I had thought you had just run a different test and didn't first realize that you had changed the upload handling.

**Comment by bilalshaikh42** [comment]
> Takeways
> 
> * The issue seems to be with the resources of the deployment, rather than the logic in the code
> * I think more resources need to be allocated to Redis, dispatch service, and API
> * If the above isn't sufficient, we may need to be more careful about popping tasks off our queues and only popping them off once the task is complete rather than when the task starts to avoid losing track of tasks

Redis is only failing here due to the combine archives being stored there.
The queue actually already has this sort of retry built-in. If you recall, earlier we used to have the problem where the dispatch service crashing would cause the state of the simulation to get stuck. Switching to the [bull-based](https://github.com/OptimalBits/bull) queue resolved this by not having the task popped off until it was completed. However, this will not survive the Redis container itself failing

> * We could consider throttling the processing of the dispatch queue

This seems like the wrong approach. All of these problems would disappear if we  slow down the processing, but that seems like throwing the baby out the with bathwater

**Comment by bilalshaikh42** [comment]
@jonrkarr I would advocate for reverting these changes and releasing them back to where we were. 
The changes also conflict with the changes I started working on after the meeting today. 
Though it may be more work, I think code reviews would be quite helpful in iterating major design changes  and preventing conflicts and reverts

**Comment by jonrkarr** [comment]
I think this is the right direction to proceed, moving the main work to the queues rather than the API. 

The archives could be moved to a different temporary storage. This would alleviate what appears to be the source of all above errors. 

I'm not convinced redis couldn't be a mechanism to store archives with a different configuration. Others do use it with bull very similar to this for temporarily holding binary files, despite this not being the intention of redis. I think this is worth trying since it's an easy change.

**Comment by jonrkarr** [comment]
Unfortunately, this is hard to test except with deploying it.  There isn't a easy way to fully replicate this locally.

**Comment by bilalshaikh42** [comment]
> I think this is the right direction to proceed, moving the main work to the queues rather than the API. 

I agree. I have started working on moving the extraction to a processing queue rather than the API. 

What was originally the "complete processor" has become a catch-all that is almost entirely responsible for error handling. That is causing a constraint on where error messages can be reported. 
A simple way to get around this is to have front end display the "status reason" field instead of just the logs in case of failure. This will return the logs object to it's intended purpose of simulation execution information and allow us to cleanly separate the processing steps instead of cramming everything into the complete processor. 


> The archives could be moved to a different temporary storage. This would alleviate what appears to be the source of all above errors. 

This is the part that I am unsure of. No matter where the archive is stored, fundamentally the API needs to recieve it and send it somewhere else. No matter the storage mechanism the amount of work is roughly on the same order. 

It's possible that the UConn bucket is not as performant as some other storage, but changing it is not fundamentaally reducing the amount of work/traffic needed. 

Moving the extraction step on the other hand, I agree, is going to significantly change the amount of work and network transfer needed. 

The approach I am taking is to upload the image to S3 as normal, but shift the extraction to a work queue. 

If we really need to, we can send a response to the client and then upload the file later. Even then, I see no reason uploading it to redis is a better option that just uploading it to S3 directly. 


> I'm not convinced redis couldn't be a mechanism to store archives with a different configuration. Others do use it with bull very similar to this for temporarily holding binary files, despite this not being the intention of redis. I think this is worth trying since it's an easy change. 

I am very skeptical this is viable for a few reasons. I can see this working for small text files, but not large binary data. 

- Redis values are limited to 512mb, which is smaller than our filesize limit.  We would need to split larger files into pieces

- we would need to manage memory usage carefully since these files are going to be kept in memory on a single redis container. Something like 20 simultaneous simulations would be enough to have redis using 4-5gb of memory which is quite expensive. This is what was leading to all the issues with the queue. 
The redis [ebook](https://redis.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-6-distributing-files-with-redis/6-6-2-sending-files/) shows an example of file transfer using Redis, and it is quite more complicated that just uploading the file to S3 directly.   Even if we do, fundamentally it's the same amount of work as mentioned above. 

- redis lookup time scales with amount of data stored. If we start adding files, our queues performance will degrade rapidly. The queues, especially for monitoring the runs, are sending very many requests of very small amounts of data, so adding time to lookup will not scale well.

**Comment by jonrkarr** [comment]
There are various ways to work around the current issue. 
- We could set up a persistent volume. This would be much more performant than a Uconn or Google S3 bucket. 
- We could limit uploads to a smaller size, with larger archives having to be submitted via URL. We already had this concept. Physiome could, for example, upload their archives to an S3 bucket and then biosimulations their urls.

The points you raise about extraction and processing don't seem directly related to this. While this would be an improvement in design, it's unclear to me that this needs to be changed. It wouldn't address the storage bottleneck that this thread tries to relieve, which requires moving the downloading and saving of archives to after the api returns its initial response.

**Comment by jonrkarr** [comment]
Next steps
- [ ] Increase resources to HSDS to address the most frequent failure above.
- [x] Switch model repositories to submit archives via URLs. We can ask Mike to create additional S3 buckets. GitHub/GitHub LFS is another option, but that requires committing files.
- [ ] Switch temporary archive storage from Redis to a persistent volume (persistent disk HDD block storage) or potentially an S3 bucket. This will be much more performant than the UConn S3 bucket. If HDD isn't fast enough, SSD is also an option. This will allow the API to quickly save file uploads and return responses without requiring a lot of memory. This should avoid overloading Redis, which should address most of the other above problems.
- [ ] We could potentially reduce the maximum upload size to say 64 MB, requiring larger archives to be submitted via URLs. This would help control the amount of persistent disk that we need.

Ideally the processors would refactored so that the tasks are broken down to smaller tasks, and the tasks are atomic. But, this doesn't seem strictly necessary. In the interest of focusing on content, this can be left for the future.

**Comment by jonrkarr** [comment]
I changed BiGG to submit archives via URLs for an S3 bucket. For now, I used a prefix in the `biosimdev` bucket. I can switch the configuration to a separate bucket once we have one.

Observations
- This permits MUCH faster submission.
- Our system successfully queued jobs and executed them (it accepted jobs much faster than it executed them, and correctly held the excess jobs in its queue)
- Only 3 of 88 jobs failed
   - 2 jobs: `ERROR 2022-01-08 23:34:29,175 hsload.py:310 Error creating file /results/61da651f837f3f112d0b6a61: [Errno 409] Conflict`
     - Example: 61da651c1c6f7b2e7561c15c
   - 1 job: Job state was never updated to `SUCCEEDED`
     - SED-ML saved twice
     - Log not saved (YAML: 8.2 MB)
     - This is hard to debug because the processing of this run is missing from the log, although it did start and mostly succeeded. It feels like the pod may have failed during its processing.
     - Example: 61da6521837f3f112d0b6a68
- API, HSDS, simulators API and maybe other pods failed

Next steps
- [ ] Fix updating of run state. I noticed this problem with the logic in the dispatch service a couple weeks ago and tried to correct it. It looks like there's at least 1 more case that needs to be corrected.
- [ ] Add resources to HSDS
- [ ] Switch temporary archive storage from Redis to a persistent volume (persistent disk HDD block storage) or potentially an S3 bucket
- [ ] Maybe address causes for API and simulator pods failing -- summaries of simulation runs? and ?.

**Comment by bilalshaikh42** [comment]
> * We could set up a persistent volume. This would be much more performant than a Uconn or Google S3 bucke

Yes, saving locally would be faster. But eventually, this needs to be sent to the backend. This is can either be done synchronously or asynchronously, which is the same underlying architecture we have now. The only question is whether or not to send the file to the storage before or after the response to the user.



> [ ] Switch temporary archive storage from Redis to a persistent volume (persistent disk HDD block storage) or potentially an S3 bucket

> [ ] Switch temporary archive storage from Redis to a persistent volume (persistent disk HDD block storage) or potentially an S3 bucket. This will be much more performant than the UConn S3 bucket. If HDD isn't fast enough, SSD is also an option. This will allow the API to quickly save file uploads and return responses without requiring a lot of memory. This should avoid overloading Redis, which should address most of the other above problems.

Persistent volumes cannot be shared between pods. This was the whole reason we had to ask UConn for an NFS share and then eventually an s3 bucket. Again, here if using an s3 bucket, this is identical to what we had before, except that the response is sent to the user before processing, which is just a matter of removing an `await` and adding an appropriate callback. 

>The points you raise about extraction and processing don't seem directly related to this. While this would be an improvement in design, it's unclear to me that this needs to be changed. It wouldn't address the storage bottleneck that this thread tries to relieve, which requires moving the downloading and saving of archives to after the api returns its initial response.

This is exactly what I have been trying to say. Sorry If I was not clear. the only real change that is needed is the order of operations. First, the API sends the response to the user, then it goes through and downloads the archive (if via URL) and uploads it to the s3 bucket. This keeps everything much simpler than sending files around in a method other than an s3 URL.

**Comment by jonrkarr** [comment]
I wasn't aware that persistent storage can't be attached to multiple pods. Lets use a Google bucket with an S3-compatible API. This will be different than before
- Large archives will be downloaded by the dispatch-service AFTER the run is created. Uploads can be limited to smaller sizes. Users with large archives can be asked to use URLs. This will ensure that the API can quickly save files sent to it and return a response. This also allows the API to accept submissions much more rapidly.
- Model repositories upload archives to S3 buckets and provide URLs to our API.
- Archives are saved to S3 AFTER the run is created and a response is returned to the client.
- The connection to the bucket will be faster than to UConn's bucket. Based on our experience, it will also be more reliable, addressing issues I saw in December.
- This limits the workload on the API, shifting more of the work to the dispatch service where queues are set up to manage it.

We will only need a small amount of Google storage because we'll only use this bucket for temporary storage; we will still use the UConn bucket to accumulate projects and their results. The dispatch service can delete these files after its done with them. In addition, we can set a life cycle policy to be sure these temporary files get cleaned up.

Based on my experience on Saturday, this combined with another change I made will leave just 1 type of error that affected 1 of 88 runs.

**Comment by bilalshaikh42** [comment]
> * Large archives will be downloaded by the dispatch-service AFTER the run is created. Uploads can be limited to smaller sizes. Users with large archives can be asked to use URLs. This will ensure that the API can quickly save files sent to it and return a response. This also allows the API to accept submissions much more rapidly.
> Archives are saved to S3 AFTER the run is created and a response is returned to the client.

Are user uploaded archives uploaded to google storage by the API?

**Comment by jonrkarr** [comment]
Yes, the API will save user-uploaded archives to a Google bucket. The performance can be further managed by restricting user uploads to a small size. This is fine because we allow larger archives via URLs.

Separately, biosimulations-bigg, biosimulations-physiome, etc. can upload archives to a UConn bucket, provide the API their URLs, and the dispatch service can download them. This is already working for biosimulations-bigg. The changes I added already implement this. In my experience over the weekend, this allows much faster submission.

**Comment by bilalshaikh42** [comment]
Looking at the logs of the` first submission after changing the buckets over to google cloud.
```
[Nest] 1  - 01/16/2022, 9:14:42 PM   DEBUG [SimulationRunService] Downloading file from https://github.com/biosimulators/Biosimulators_test_suite/raw/deploy/examples/sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-continuous.omex ...
33
[Nest] 1  - 01/16/2022, 9:14:42 PM   DEBUG [SimulationRunService] Downloaded file from https://github.com/biosimulators/Biosimulators_test_suite/raw/deploy/examples/sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-continuous.omex.
32
[Nest] 1  - 01/16/2022, 9:14:42 PM   DEBUG [SimulationRunService] Uploaded simulation archive to S3: https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/archive.omex
31
[Nest] 1  - 01/16/2022, 9:14:42 PM   DEBUG [SimulationStorageService] Extracting simulations/61e48ac265c3ed8c9352bc7b/archive.omex to simulations/61e48ac265c3ed8c9352bc7b/contents
30
[Nest] 1  - 01/16/2022, 9:14:43 PM   DEBUG [SimulationRunService] Uploaded archive contents: ["https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/metadata.rdf","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/Figure1.jpg","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/expected-results.json","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/Figure2.jpg","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/manifest.xml","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/BIOMD0000000297_url.xml","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/reports.h5","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/simulation_1.sedml","https://storage.googleapis.com/files.biosimulations.dev/simulations/61e48ac265c3ed8c9352bc7b/contents/Figure3.vg.json"]
29
[Nest] 1  - 01/16/2022, 9:14:46 PM     LOG [SimulationRunController] Patch called for simulation run '61e48ac265c3ed8c9352bc7b' with {"status":"QUEUED","statusReason":"Simulation run job is queued for execution."}
```
It seems the file was downloaded from github, uploaded to the s3 bucket, extracted, saved to the bucket and submitted for simulation all within 3 seconds. I think it is now clear that the bucket was a major bottleneck. I'll start some testing to see how this works under load

**Comment by jonrkarr** [comment]
My intuition is that the UConn bucket wasn't an insignificant bottleneck. Do you know roughly how long the same operations took with the UConn bucket?

**Comment by jonrkarr** [comment]
@bilalshaikh42 I think this can be closed
