### ISSUE TITLE
🐛:  SVGs are displayed as Zipped SVGs

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3934]
### Location

runBiosimulations

### What happened?

SVG files are displayed as Zipped SVG files even if they have the regular ".svg" extension
https://run.biosimulations.dev/simulations/61cf6049e3202b690abca986#tab=files

### What made it happen?

Run a simulation that contains an svg file. For example  https://run.biosimulations.dev/simulations/61cf6049e3202b690abca986#tab=files

### Version

Development (Deployed on a .dev domain)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
Probably due to recent changes in #3931 and how the onology api is using that information to lookup file descriptions/names

**Comment by jonrkarr** [comment]
Yes, its due to the PR cited above. Our apps use the format URI, not the extension. Unfortunately, SVGZ doesn't have its own canonical media type. As a result, I used the same URI for both SVG and SVGZ. 

One option is to use a different media type for SVGZ such as `image/svg+xml-compressed` as suggested in w3c/svgwg#701. This would entail a few small changes:
- [x] Modify https://github.com/biosimulations/biosimulations/blob/dev/libs/ontology/extra-sources/src/lib/edam-biosimulations-formats.json#L1121
- [x] Modify BioSimulators-utils
- [ ] Rebuild and re-submit COMBINE archives for Physiome

@bilalshaikh42 thoughts?

A long-term solution it to register unique terms for SVG and SVGZ with EDAM and use EDAM URIs. This would be a more elegant solution, but the timeline is indefinite because EDAM has been very slow to approve and release changes.

**Comment by jonrkarr** [comment]
I can take care of the first two tasks as part of supporting the other file formats discovered in Physiome.

**Comment by bilalshaikh42** [comment]
I agree with the long-term solution. 
In the short term, I think it would make more sense to default the other way. Meaning, it is acceptable to label SVGZ files as regular SVG files, since users familliar with SVGZ files would understand the intent.  For most users however, showing the common SVGs as an unexpected format may cause confusion.

**Comment by bilalshaikh42** [comment]
Having read through the issue, I think agree that the simplest solution would be to just label the SVGZ files as 
```image/svg+xml-compressed```. 
The worst-case consequences of using the nonstandard mimetype will be some programs that rely exclusively on mime-type not recognizing it, but this seems to happen anyway since they try to interpret the file as SVG without running any sort of decompression leading to errors. The alternative of not recognizing the mimetype actually seems better to me.

**Comment by jonrkarr** [comment]
I changed the media type/URI for SVGZ in #3937. Using a non-standard media type/URI allows us to print a more informative description than something like "Unknown binary format". The downside seems minimal to me because using a non-standard media type doesn't seem worse than using none at all.
