### ISSUE TITLE
Use Github Flavored Markdown for project descriptions

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3963]
818d2673f20c1a87f235618cae242c129b49630f adds support for markdown on project descriptions but explicitly sets it to support original flavor rather than GitHub flavor. GitHub flavored markdown seems to be more widely supported these days and the use case for displaying markdown on GitHub and project descriptions is quite similar.  It also provides additional extensions that may be useful for project authors. 

@jonrkarr Was there a particular reason you chose to disable gfm in this line?https://github.com/biosimulations/biosimulations/blob/f75185dd4b296de8a817a71b84512c6644a85252/libs/simulation-runs/ui/src/lib/simulation-runs-ui.module.ts#L38

**Comment by jonrkarr** [comment]
I agree we would preferably use CommonMark or GFM (which is similar to CommonMark). We've been using ngx-markdown to render markdown. However, the package underlying ngx-markdown, marked.js, is only partially compatible with GFM. See https://marked.js.org/#specifications and https://github.com/markedjs/marked/discussions/1202#discussioncomment-168112.

Alternatively, we could switch to a different library which does support CommonMark/GFM, such as [remark](https://remark.js.org/).

This would require
- [ ] Switch to rendering markdown with an alternative package, such as [remark](https://remark.js.org/), rather than ngx-markdown.
- [ ] Update documentation to say we support GFM rather than original markdown
- [ ] Expand documentation to note support (or lack of) for code highlighting, including which languages are supported

**Comment by bilalshaikh42** [comment]
Looking at the discussion regarding compatibility, it seems that for most _practical_ purposes the underlying library is compatible. Ngx-markdown is nice in that provides angular style services, directives, and pipes that manage the underlying library for us. We could simply enable gfm and see if there are any issues that we notice 

There are some issues with edge cases, but I do not anticipate that these will pop up often.
 
https://github.com/markedjs/marked/discussions/1202#discussioncomment-168114

**Comment by jonrkarr** [comment]
I was aiming to be more conservative so that we don't confuse users with incomplete markdown support. Alternatively, we can go with gfm, but document the incompatibility.

Lets go with this compromise:
- [x] Switch ngx-markdown configuration to use gfm
- [x] Update documentation to note that we support gfm
- [x] Add a note in the documentation that gfm support is incomplete and include a link to https://github.com/markedjs/marked/discussions/1202#discussioncomment-168114.

**Comment by bilalshaikh42** [comment]
Sounds good. I can do that
