### ISSUE TITLE
Add test to CI that Docker images start and respond as intended

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3978]
As noted in #3977, images can build successfully but fail to start. Our CI/CD pipeline is missing this because its not testing most of the images. This gap could be shrunk by checking that the images  start up successfully and return positive health responses.

**Comment by bilalshaikh42** [comment]
This is a good point.
The CD system (argo deployments) is aware of this, and actually tests the health endpoints of the images before deployment. That is the reason that the deployments continued to work even though the image was crashing.

**Comment by bilalshaikh42** [comment]
Including this in the CI would be ideal.  I am not sure how to create workflows in GitHub actions that can start a docker container, run tests against it, and then close it down properly, however. 
 I don't want to run the tests themselves in the docker image because then we are adding a lot of dependencies to the container and then we are effectively testing a different image than the one that is deployed
We could just add a simple API call to the deployment server that checks to see if the dev deployment worked, and raise an error if not.  That is a part of the goal of #3421. However, this would not test  things properly on PRs

**Comment by bilalshaikh42** [comment]
Here is a potential approach to running this sort of test. All we need to do is curl the /health endpoint for each container

https://stackoverflow.com/questions/67134410/how-to-test-my-dockerfile-for-my-python-project-using-github-actions

**Comment by bilalshaikh42** [comment]
https://dev.to/mihinduranasinghe/using-docker-containers-in-jobs-github-actions-3eof

This might be a good approach to do this. We can use the containers that were just created to run a quick test against the health endpoint. For the API, we will need to provide a mongo, nats, redis and some config as well to get the container to start

**Comment by jonrkarr** [comment]
As another example, the unit tests for the COMBINE API are being run in the Docker image.

Yes, this would require mocking some other resources or a little refactoring to enable minimal testing without other resources (this would narrow, but not close the testing gap; even this would be helpful).
