### ISSUE TITLE
Requests for non-existent results kill API pods

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4007]
Example: https://api.biosimulations.dev/results/xxx?includeData=false

For reasons I don't understand, this generates a severe error which requires restarting the pod.

**Comment by bilalshaikh42** [comment]
Interesting. This can be replicated locally as well. Seems to be caused by an unhandled aync error. Looks like after the initial 404, there is another 404 that occurs but is not caught, probably due to retrying.

**Comment by bilalshaikh42** [comment]
@jonrkarr should I work on this?

**Comment by jonrkarr** [comment]
Although this seems unrelated to issues we're having with API performance (our codes shouldn't be generating such errors), maybe this provides a window into some issues we're having with the API pods. For that reason, please try to handle the error.

Retrying is intended to be limited to 500 level errors. 404 errors aren't intended to be retried.

**Comment by bilalshaikh42** [comment]
Caused by https://github.com/biosimulations/Biosimulations/blob/f206559bd2d0ceb92241c56f711a7790d0fdbb1f/apps/api/src/results/results.service.ts#L43 

The first promise is not awaited until later in the method. If the second promise fails, the first will continue to execute, leading to an uncaught promise exception.
