### ISSUE TITLE
Add simulators to renovate ignore list. 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4025]
Commit ad80e4fa6d4534bfaffd61f4acce4222c8fc7be4 was an automated update of amici
@jonrkarr I assume you want to handle this manually? If so we need to add the python dependencies that you do not want to have updated to the renovate.json file.

**Comment by jonrkarr** [comment]
Renovate can try updates. The tests and docker building should be able to catch problems.

I think that AMICI constraint can be removed. AMICI doesn't require Sympy>=1.9. I must have misattributed that constraint.

**Comment by jonrkarr** [comment]
I had this correct. AMICI requires Sympy >= 1.9, which I believe is still a problem for CBMPy (although not reflected in its requirements). 

https://github.com/AMICI-dev/AMICI/blob/v0.11.22/python/sdist/setup.cfg#L30

I just verified that when Sympy 1.9 is installed, one of the unit tests does fail.

The tests passed because AMICI and Sympy weren't updated in `Pipfile.lock`. The Dockerfile uses `pipenv install --system --deploy`. This must only rely on `Pipfile.lock`.

This means that renovate is making `Pipfile` and `Pipfile.lock` diverge, which will be confusing. I think renovate can be useful to run to alert us to possible updates. @bilalshaikh42 Can you disable auto-approval for PRs by renovate involving `Pipfile` or `Pipfile.lock`?

**Comment by bilalshaikh42** [comment]
The commit does seem to show that the pipfile.lock was updated
https://github.com/biosimulations/biosimulations/pull/4021/files#diff-0e8ef327d054a578fd1a4682a14049c00d8272c25805ab1e638b45616434dfc9

Is there some special flag that is needed to include amici in the install similar to pip? 

But in anycase, I can disabled auto merge for the python packages

**Comment by jonrkarr** [comment]
Renovate divergently updated `pipefile` and `pipefile.lock`.

The extra AMICI constraint is to hack pipenv to resolve a set of dependencies that satisfy all of the version constraints. Without that line pipenv fails, saying that it can't resolve an environment. In principle, that line shouldn't be needed. The other lines (and their dependencies) already contain the same information. The additional line seems to help pipenv find a set of versions that match the constraints. Unfortunately, the PyPI/Pip ecosystem is not as good as NPM.

**Comment by jonrkarr** [comment]
A few of the other lines in `Pipefile` serve a similar purpose, to help pipenv resolve an environment. The lines that shouldn't be needed have comments.
