### ISSUE TITLE
Add requirements.txt file or move pipfile to root directory

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4028]
There should either be a requirements.txt file or the pip file should be in a more standard location for developers to install needed packages to ruin combine API

**Comment by jonrkarr** [comment]
I suggest we leave them where they are. While, its tempting to think of this as similar to the nx `project.json` files, there are some important differences.

I moved this to the COMBINE-API directory because these are specific to the COMBINE API app. Any other Python app should have its own environment, especially because the COMBINE API has many requirements.

What is in a "standard" location is the `Dockerfile`. I tried to clearly label the assets for this.

Developers should follow the `Dockerfile` because `Pipfile`/`Pipfile.lock` is not a sufficient description of the environment. Due to quirks/bugs of pipenv, those files do not capture all packages that need to be installed. Those files are somewhat intentionally located in a subdirectory for this reason, to avoid giving the false impression that they are sufficient. (Because `Pipfile`/`Pipfile.lock`, most work can be done with that alone without the extra steps from the `Dockerfile`.)

In addition, since we're using nx + python + pipenv, there is no standard.

Furthermore, I suggest we do not try to use a `requirements.txt` file plus a `Pipfile`; this would create extra work to maintain.
