### ISSUE TITLE
If API is down, dispatch service attempts to post logs leading to 409 conflict

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4031]
Cannot trace exactly where this is happening, but am still getting 409 errors on logs

**Comment by bilalshaikh42** [comment]
fixed by deleting and restarting redis. Need to look into how the queue removes jobs after failure. If we are not intending to retry the job, then it should be removed from the queue

**Comment by bilalshaikh42** [comment]
This occurs if the metadata step fails. 
```
Nest] 1881307  - 01/11/2022, 12:52:03 PM   ERROR [SimulationRunService] Error Request failed with status code 409 for post operation on path http://localhost:3333/metadata/61ddc2477668ca1d1ac43ab6 for simulation run 61ddc2477668ca1d1ac43ab6
[Nest] 1881307  - 01/11/2022, 12:52:03 PM   ERROR [MetadataService] Failed to post metadata for simulation run '61ddc2477668ca1d1ac43ab6': [object Object].

/home/bilal/Projects/work/Biosimulations/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 409
    at createError (/home/bilal/Projects/work/Biosimulations/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/bilal/Projects/work/Biosimulations/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/bilal/Projects/work/Biosimulations/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
^[
```
EDIT: this is now a 409 on metadata, not logs

**Comment by jonrkarr** [comment]
That doesn't sound right. There's no specific connection between the logs and any of the individual post-processsing steps.

**Comment by bilalshaikh42** [comment]
Yup, sorry, misread the log

**Comment by bilalshaikh42** [comment]
This is on a different endpoint than before

**Comment by jonrkarr** [comment]
I haven't seen 409 errors with the logs.

**Comment by bilalshaikh42** [comment]
I am consistently seeing them locally. I think this only occurs in specific cases involving the API or combine service going down

**Comment by bilalshaikh42** [comment]
I believe  this is caused when the complete processor is interrupted. The queue then considers the entire job as failed. I think breaking this up into pieces will help.

**Comment by jonrkarr** [comment]
Posting logs once at the very end would be sufficient. I don't think we need to post and update. I post and updated so logs would be available before post-processing completes. This make things more complicated. We could simplify this by posting once.

Simplified workflow:
1. Run simulation
2. Post-process results
3. Try posting structured log
4. If unsuccessful (because the schema of the log is invalid), post plain text log

Even steps 3-4 could be collapsed to a single HTTP call to the API if its possible to perform validation without going through an HTTP call. I suspect this is more difficult than its worth. For that reason, we probably should stick with the workflow above.
