### ISSUE TITLE
Fix OpenAPI errors

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4061]
The API is no longer OpenAPI-compliant. Ideally, we'd be compliant. But this isn't necessary or possible.
SEe https://github.com/biosimulations/biosimulations/actions/runs/1702900921

**Comment by bilalshaikh42** [comment]
This seems to be caused by the strange class name issue that you mentioned in #4036. The class names that are being flagged here have the same strangely transformed names such as "$P".

**Comment by bilalshaikh42** [comment]
This seems to be caused by the optimization of the "production" build.
 Both running the API via `nx serve api` and first building it via `nx build API && node dists/apps/api/main.js` result in an openapi.json file that passes the Open API tests just fine. However, `nx build API --configuration=production && node dists/apps/api/main.js` has this problem. I wonder if there was a recent change to the build optimization that now minified class names.

**Comment by bilalshaikh42** [comment]
yup, that is it
https://github.com/nrwl/nx/issues/8446

This would also explain the validation errors in #4036 as the validation is dependent on reflection, which in turn requires class names to stay consistent.
