### ISSUE TITLE
Confirm `EndpointLoader` receives correct configuration

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4287]
I'm trying to understand why the COMBINE API responses appear to be slow. I doubt its because external URLs are being used rather than internal URLs. Nevertheless, @bilalshaikh42 is the configuration for the `EndpointLoader` set up correctly? I can't find the environment variables defined anywhere. It looks like the URLs are always external.

- `API_URL`
- `SIMULATORS_API_URL`
- `COMBINE_API_URL`
- `DATA_SERVICE_URL`

https://github.com/biosimulations/biosimulations/blob/760b80d78dd87a7551adb4d828965c6025847509/libs/config/common/src/lib/endpointLoader.ts#L212

**Comment by bilalshaikh42** [comment]
The endpoint loader is setup so that this could be configured if desired. At the moment, all the env variables in the actual deployment are set to use the external URLS. This could be changed by setting the variables you mentioned above to the internal versions and then adding the corresponding external variables in the config for each app in the deployment.

**Comment by jonrkarr** [comment]
Does that mean data has to transit in and out of the cluster?

**Comment by bilalshaikh42** [comment]
yes, that way everything is going through the ingress, so we get logging/data on the network calls. I don't think this is much of a problem, however. Google's internal networking should route this quite efficiently. 
The issue with the combine API was the python process in the container timing out, not the network requests.

**Comment by jonrkarr** [comment]
I asked about network requests because the data transfer (granted to my browser) is a significant part of the overall response time.
