### ISSUE TITLE
`ManifestProcessor` seems to be called to early

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4322]
The `ManifestProcessor` seems to frequently raise errors on its first try. I think because it tries to access the manifest before its been posted to S3. It sounds like the dependency on the ExtractProcessor needs to be corrected.

**Comment by bilalshaikh42** [comment]
This is strange, since this was never an issue previously. This must have been causes by the change to use the manifest file rather than the combine archive directly.

**Comment by bilalshaikh42** [comment]
Looking at the code, the manifest processing step  does not have any dependencies defined since previously it was simply using the combine archive to get the manifest. Now that it is dependent on the extraction happening, there will need to be some significant changes to the processing flow.

@jonrkarr I can make the dependency changes, but a simpler solution might be to restore the behavior of using the combine archive directly for now
