### ISSUE TITLE
Enable CORS for LibreText

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4337]
https://bio.libretexts.org is currently enabled. @LibreText appears to be using a new domain because they report CORS is blcoked. @Miniland1333 please let us know what domain you need enabled.

The new LibreText domain should be added at 
https://github.com/biosimulations/biosimulations/blob/146b327b72b1d60beedc7a51a5a47e31cceb4977/apps/api/src/main.ts#L47

**Comment by Miniland1333** [comment]
I was actually attempting to access `"https://api.biosimulators.org/simulators/vcell/latest?includeTests=false"` from bio.libretexts.org (the API for seeing which simulator versions are available), which was what was returning the CORS error. Since you gave me the better solution of using "latest" for simulationVersion, the current CORS settings are okay.

I think possibly the only change you may want to address before closing out this issue is somehow synchronizing the allowedOrigins to some extent between `biosimulators.org` and `biosimulations.org` so that you have one whitelist that is shared between the two APIs.

**Comment by jonrkarr** [comment]
Yes, the APIs have presently have separate white lists. Ideally we would factor this out to our configuration.
