### ISSUE TITLE
Some OpenCOR simulations fail

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4394]
This seems to be a common failure
```
Traceback (most recent call last):
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 247, in 
    if not update_paths(args.path, args.scripts_dir, args.clear_args, args.extra_args):
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 213, in update_paths
    update_scripts(scripts_dir, new_path, clear_args, extra_args)
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 125, in update_scripts
    update_script(os.path.join(bin_dir, fn), new_path, clear_args, extra_args)
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 118, in update_script
    with open(script_filename, 'w') as f:
OSError: [Errno 30] Read-only file system: '/home/opencor/OpenCOR/bin/../python/bin/biosimulators-utils'
```

For example: https://run.biosimulations.org/runs/623c012520a7bb7518fbb5fb#tab=log

**Comment by bilalshaikh42** [comment]
@jonrkarr it seems somewhere in the docker image (not sure if opencor itself, or our wrapper) there is an explicit path to the "opencor" users home directory, which is not going to be available on the HPC when used as a singularity container.

**Comment by jonrkarr** [comment]
The real problem is a SED-ML error. This is clearly indicated lower in the log. 

It seems that OpenCOR is trying to save a file (`/home/opencor/OpenCOR/bin/../python/bin/biosimulators-utils`) to part of the file system that is read-only when converted to Singularity. I guess OpenCOR only tries to do this on failures. OpenCOR does try to catch errors, but not the type this raises. I filed this issue as opencor/opencor#2609 and submitted PR opencor/opencor#2610 to fix it.
