### ISSUE TITLE
Setup error logging

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#705]
It will likely be helpful to log errors encountered by users.
- REST API errors
- JavaScript errors

One option is [AirBrake](https://airbrake.io). I've setup AirBrake for datanator. While there are several similar services, AirBrake is the only one I found which is free for teams (for up to 7.5k errors per month). However, AirBrake doesn't seem to have great integration with modern Angular.

AirBrake and other services have a few useful features
- Group errors
- Automatically create GitHub issues for errors encountered in production mode

**Comment by bilalshaikh42** [comment]
Since we have a Kubernetes cluster, we should be able to self host the ELK stack. This can give us quite advanced logging and analysis across the hosted api, website, various internal services etc. 
They stack is designed to play well with docker, so deployment of the stack should be just a few lines in our Kubernetes config, and we wont need to rely on a third party service which will be holding all the data. 

https://www.elastic.co/logstash
https://www.elastic.co/kibana

**Comment by bilalshaikh42** [comment]
The elastic stack includes APM, which is an application performance monitor server.  This can monitor performance of all the backend apps, and well as communication and networking between them. 
[APM info](https://www.elastic.co/apm)

The front end user apps can use [this integration](https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html) to send information to the APM.  This would include the error intercepting similar to Airbrake, as well as general performance and bottleneck info. It would also replace the need for google analytics

Auth0 can also send logging info into logstash, which can also be loaded into the stack

**Comment by bilalshaikh42** [comment]
Jaeger tracing is enabled for the dev deployment. The UI is available at 
https://tracing.api.biosimulations.dev

We now need to send logging messages to the collector: 
https://github.com/biosimulations/Biosimulations/wiki/Tracing
